### ISSUE TITLE
position of nagvis hover popup window

### ISSUE THREAD

**Issue by equick** [NagVis/nagvis#1]
Hi, 

I'm trying to embed a nagvis map on my site here http://linuxproblems.org/wiki/Dashboard but when hovering over a host, the popup window is positioned in the wrong place. This works fine in NagVis itself , so not sure how much help I'm going to get here, but just wondered if there was a particular css property I could override to fix this?

Thanks,
Edward

**Comment by LaMi-** [comment]
Hm, the hover menu is positioned correctly. Only the context menu (right click) is positioned wrong.
Please try to put NagVis as iframe into the page. This might solve these kind of problems.

**Comment by equick** [comment]
Yes I played around with the code and managed to fix it. I'm using a mediawiki extension to display the map http://www.mediawiki.org/wiki/Extension:NagVis although not sure the developer is maintaining it any longer as the download site is down. I will look into the iframe option anyway. Thanks for the reply!
