### ISSUE TITLE
Javascript error g_map_names is not defined

### ISSUE THREAD

**Issue by li73772** [NagVis/nagvis#10]
Hi,

If I open any of the maps I see following error.

Javascript error occured: ReferenceError: g_map_names is not defined http://192.168.20.22/nagvis/userfiles/templates/default.header.js (118)

- Stacktrace -
printStackTrace.implementation.prototype.run@http://192.168.20.22/nagvis/frontend/nagvis-js/js/NagVisCompressed.js:1:370
printStackTrace@http://192.168.20.22/nagvis/frontend/nagvis-js/js/NagVisCompressed.js:1:134
handleJSError@http://192.168.20.22/nagvis/frontend/nagvis-js/js/NagVisCompressed.js:531:3

I´ve changed in config.ini.php the following parameters:
header_show_states=0
showmaps=0
showrotations=0
;[rotation_demo]
;maps="demo-germany,demo-ham-racks,demo-load,demo-muc-srv1,demo-geomap,demo-automap"
;interval=15

My System:
Nagvis 1.8.1
Firefox 17.0.10/Firefox 36.0.1/IE 8.0 (same behavior for all of them)

**Comment by LaMi-** [comment]
Hi,

I can not reproduce this issue, but in the past there were users having 
this problem with customized templates or javascript files which were 
not compatible to the current code anymore.

Regards
Lars

On 13.03.2015 07:09, li73772 wrote:
>
> Hi,
>
> If I open any of the maps I see following error.
>
> Javascript error occured: ReferenceError: g_map_names is not defined 
> http://192.168.20.22/nagvis/userfiles/templates/default.header.js (118)
>
>   * Stacktrace -
>     printStackTrace.implementation.prototype.run@http://192.168.20.22/nagvis/frontend/nagvis-js/js/NagVisCompressed.js:1:370
>     printStackTrace@http://192.168.20.22/nagvis/frontend/nagvis-js/js/NagVisCompressed.js:1:134
>     handleJSError@http://192.168.20.22/nagvis/frontend/nagvis-js/js/NagVisCompressed.js:531:3
>
>
> I´ve changed in config.ini.php the following parameters:
> header_show_states=0
> showmaps=0
> showrotations=0
> ;[rotation_demo]
> ;maps="demo-germany,demo-ham-racks,demo-load,demo-muc-srv1,demo-geomap,demo-automap"
> ;interval=15
>
> My System:
> Nagvis 1.8.1
> Firefox 17.0.10/Firefox 36.0.1/IE 8.0 (same behavior for all of them)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NagVis/nagvis/issues/10>.
>


-- 
Lars Michelsen IT
Keltenstraße 4
85586 Poing

Mobile: +49 151 26965801
E-Mail: lm@larsmichelsen.com

**Comment by LaMi-** [comment]
Got it! It occured when setting header_show_states=0 in config file. Just fixed it in git.
