### ISSUE TITLE
Add support for lmd

### ISSUE THREAD

**Issue by marcomusso** [NagVis/nagvis#100]
Livestatus unavailability is [major problem during core restarts](https://monitoring-portal.org/index.php?thread/40031-nagvis-maps-go-blue-on-nagios-reload/).
Supporting [lmd](https://github.com/sni/lmd) as a livestatus caching layer would solve the problem, is there any plan on doing this?
Are there any known solution to this problem?

**Comment by LarsMichelsen** [comment]
In some cases doing a core reload instead of a restart could possibly be a workaround.

Maybe I did not understood lmd correctly, but it should be working transpartent for the clients (NagVis). This means you should be able to connect NagVis just by pointing it to a LMD socket

**Comment by marcomusso** [comment]
It doesn't work out of the box (using lmd 1.0.3), I'll do some more tests to be able to have more info.
Reload or restart even with pre-cached objects may take too long (10-30 sec) for large installations (~100k services).
