### ISSUE TITLE
update nagvis 1.9.b14

### ISSUE THREAD

**Issue by duncillo** [NagVis/nagvis#101]
When upgrading from version 1.9b14 to 1.9b15 nagvis stops working, gives 404 error, restart does not solve the problem, any ideas?

EDIT: I use nagvis with omd, and update with omd_install.sh.

Thanks in advance

**Comment by rafaelalmeida92** [comment]
Hello duncillo, in your problem, when you tried to update your Nagvis and after you solved your problem updating your OMD, the Nagvis version continue the version that you used before or have you sucess on the Nagvis update to the next version?
