### ISSUE TITLE
Path incorrect for conf.d, install fails.

### ISSUE THREAD

**Issue by Cat5TV** [NagVis/nagvis#103]
install.sh detected the following as my apache2 conf.d:
`/etc/apache2/config-available/conf.d`
the correct path should be:
`/etc/apache2/config-available`

Should be corrected or allow the user to edit during install. Of course because there was no mkdir command before the file export, it just fails as the directory does not exist.

**Comment by LarsMichelsen** [comment]
Would be nice if you could confirm the fix.

**Comment by Cat5TV** [comment]
Thanks @LarsMichelsen - My deployment is complete so it'll be a while before my next install (on a 6 month release cycle for http://baldnerd.com/nems/ project) but will definitely try to remember to let you know  :p
