### ISSUE TITLE
No change background color on alert

### ISSUE THREAD

**Issue by duncillo** [NagVis/nagvis#104]
Hi all, 

When I receive an alert does not change the color background automatically, when manually refreshing if it changes, I have the background refresh settings, any ideas?

Edit: Which js file is responsible for making the background color change??

Edit: My version nagvis: 1.9b18

My config:

define global {
alias=Map
object_id=0
map_image=none
iconset=std_small
label_style=font-weight:bold;
label_show=0
event_on_load=1
background_color=transparent
event_repeat_interval=60
header_menu=0
label_border=transparent
event_background=1
event_repeat_duration=-1
}

**Comment by LarsMichelsen** [comment]
Just pushed a fix to the git. You can try the next daily build to get the fix.
