### ISSUE TITLE
Right click on Object - Menu behind map

### ISSUE THREAD

**Issue by davidoosting** [NagVis/nagvis#106]
When you right click on a service or host, the popup menu goes behind the map.  This happens when you click on the object in firefox to acknowlege then go back to page.

![image](https://cloud.githubusercontent.com/assets/28363480/25678295/1a0ae3e0-2ffe-11e7-98e7-cb2e2271a69e.png)

**Comment by LarsMichelsen** [comment]
Do you have a z coordinate configured for that object?

**Comment by davidoosting** [comment]
No, standard X and Y.  I cannot get it to replicate anymore.  I made no changes.
