### ISSUE TITLE
CoreAuthModPDO.php does not work with PHP Version 5.3.3

### ISSUE THREAD

**Issue by alien8r** [NagVis/nagvis#107]
Our RHEL6 boxes running the latest NagiosXI have PHP Version 5.3.3.
CoreAuthModPDO.php was added to NagVis starting with  1.9b15.
Unfortunately it kills NagVis, CoreAuthModPDO.php fails with:
`PHP Parse error:  syntax error, unexpected '[' in /oses/CoreAuthModPDO.php on line 94`

**Comment by LarsMichelsen** [comment]
Please update to the newest version. The fix is included.

**Comment by alien8r** [comment]
Tried NagVis 1.9b17 which was released this morning.
Unfortunately CoreAuthModPDO.php produces the exact same error.

**Comment by LarsMichelsen** [comment]
Let me check that.

**Comment by LarsMichelsen** [comment]
Just pushed an additional 5.3 fix with b1a121e6d0272b533d17267088bccb1d5801a994. Could you please apply it manually and report back whether or not 5.3 is now working again?

**Comment by alien8r** [comment]
Perfect it seems. Thank you.
No issues using Firefox or Chrome.
I'm sorry I wasn't able to make that change on my own, again thank you!
