### ISSUE TITLE
NagVis 1.9 incompatible with php-pecl-http

### ISSUE THREAD

**Issue by teancom** [NagVis/nagvis#112]
I realize that Nagvis doesn't require [pecl-http](http://pecl.php.net/package/pecl_http), but we have it installed everywhere for other software we run on machines with Apache+PHP. However, if it is installed, NagVis 1.9 fails to start logging this to the apache error_log:

`PHP Fatal error:  Cannot redeclare http_redirect() in /usr/share/nagvis/share/server/core/functions/html.php on line 355`

Remove pecl-http and it starts cleanly.

**Comment by teancom** [comment]
I should note that for historical reasons we're running pecl-http version 1.7.6, but according to the changelog at least, there haven't been any changes to the http_redirect function since 1.7.1.

**Comment by teancom** [comment]
I've verified that if I change the declaration in share/server/core/functions/html.php to something else ( for exampplle, http_redirecttoo) and the one call to it in share/server/core/classes/CoreLogonDialogHandler.php to the same, it works while pecl-http is installed.

**Comment by LarsMichelsen** [comment]
Should be fixed with next nightly build. Please verify and report back.

**Comment by teancom** [comment]
I just applied 8f64119 and checked, works like a champ. Thank you!
