### ISSUE TITLE
Zoom error

### ISSUE THREAD

**Issue by LaFong** [NagVis/nagvis#113]
Re-submitting bug, with correction specifying worldmap, not geomap.

I have since tested latest 1.9.b18, and get a different error when zooming:
Javascript error occured: TypeError: this.objects[parentObjId] is undefined http://localhost/nagvis/frontend/nagvis-js/js/NagVisCompressed.js?v=1.9 (4356

=========================================================
When zooming into a worldmap, level 9+, I get this error:
Javascript error occured: Uncaught TypeError: Cannot read property 'addChild' of undefined http://192.168.1.1/nagvis/frontend/nagvis-js/js/NagVisCompressed.js (4309)

We are at v1.9b8. 

I have tried it with and without NagVisCompressed.js, same error.
This error has also happened to another user, on the forum.

With latest ViewMap.js and nagvis/share/server/core/classes/ViewMapAddModify.php files, this is the debug output:

ViewMap.js:232 Uncaught TypeError: Cannot read property 'addChild' of undefined at proto.constructor.renderObject (ViewMap.js:232) at proto.constructor.initializeObjects (ViewMap.js:262) at proto.constructor.handleMapInit (ViewMap.js:136) at XMLHttpRequest.AJAX.onreadystatechange (ajax.js:95) renderObject @ ViewMap.js:232 initializeObjects @ ViewMap.js:262 handleMapInit @ ViewMap.js:136 AJAX.onreadystatechange @ ajax.js:95

**Comment by LarsMichelsen** [comment]
Is this still relevant with 1.9.11? If so, please let me know. Closing this old issue for the moment.

**Comment by ekrichbaum** [comment]
#242
