### ISSUE TITLE
change host url

### ISSUE THREAD

**Issue by sunks08** [NagVis/nagvis#115]
Hello, i'm using nagvis with centreon and i would like to change the url of my service/host to redirect to an other map ! 

In the interface of centreon the url is the same for every map so i can't redirect with a simple url.

I tried this : 
[htmlcgi]/main.php?p=243&map=[an-other-map]

But i got the error "The parameter "show" does not match the valid value format"

Thanks!

**Comment by LarsMichelsen** [comment]
I don't understand how the issue is related to NagVis. I am not using Centreon nor any NagVis integration to centreon. Maybe the devs of these solutions can help you.
