### ISSUE TITLE
How to change the host and service url from the backend

### ISSUE THREAD

**Issue by orgito** [NagVis/nagvis#116]
I'm writing a backend for our NMS (CA Performance Management). So far I can list hosts and services and get their states. I would like to set the url for the hosts and services (left click) from the backend code. 

What should I return and from which function? So far I implemented getObjects, getHostState and getServiceState. They are working well, except I would like to return a custom url and could not figure out how from reading the code.

**Comment by LarsMichelsen** [comment]
For historical reasons these settings are controlled by user configuration (nagvis.ini.php (defaults: hosturl, serviceurl,...), map globals and objects (url parameter)) and not by the backends. From my current view it would be handy to make the URL defaults be settable by the backends.

**Comment by orgito** [comment]
For the host I found out how to set the URL using the getHostMembersCount function. Now I need to find out how to do the same for services.
