### ISSUE TITLE
pnp_graph.php not found

### ISSUE THREAD

**Issue by johnLeads** [NagVis/nagvis#117]
Hi,

I am unable to find out the pnp_graph.php gadget. Please help me. I need it

Thanks

**Comment by LarsMichelsen** [comment]
I don't know which file you are talking about. If you want to display a graph image on the map use a shape object and put the full image url to the shape image surrounded by [..].

**Comment by johnLeads** [comment]
https://monitoring-portal.org/index.php?thread/34423-nagvis-gadget-pnp-graph-php-showing-in-tutorial-not-found-in-drop-down-gadget-ur/

**Comment by johnLeads** [comment]
https://support.nagios.com/forum/viewtopic.php?f=6&t=35195

**Comment by rafaelalmeida92** [comment]
Hello John,
You only need to put the URL of your pnp in the icon field of shape object of Nagvis. This information is in the documentation of Nagvis.
Regards
