### ISSUE TITLE
Extra CSSs

### ISSUE THREAD

**Issue by orgito** [NagVis/nagvis#120]
Is there a way to include extra CSS to NagVis that will be preserved after upgrades? I want to use some classes in my gadgets and would prefer not to add them inline. 

It works if I add them to /usr/local/nagvis/share/userfiles/templates/default.css. But I believe that file will be overwritten during upgrades.

**Comment by LarsMichelsen** [comment]
Have a look at the docs. There is an option "stylesheet" you could use to add a custom stylesheet file.
