### ISSUE TITLE
Problem with line

### ISSUE THREAD

**Issue by prohand** [NagVis/nagvis#121]
Hello,

When I set up a line to see the traffic of my switches they are displayed in bytes instead of Kb or Mb

The plugin used is check_centreon_snmp_traffic

**Comment by orgito** [comment]
I also would like to know how to force the line show bits per second instead of bytes per second.

**Comment by LarsMichelsen** [comment]
I can not remember how exactly this is done. It should be more flexible in the way the performance values are selected and treated (scaling, conversion to bits/bytes).

It's somehow located in share/frontend/nagvis-js/js/ElementLine.js parsePerfdata()

I am not planning to change anything bigger here.

**Comment by prohand** [comment]
Hello

I am using the plugin check_centreon_snmp_traffic I modified the following line:

`printf("|traffic_in=".$in_perfparse_traffic_str."Bits/s;$warningBit;$criticalBit;0;$speed_card traffic_out=".$out_perfparse_traffic_str."Bits/s;$warningBit;$criticalBit;0;$speed_card\n");`

By :

`printf("|load_In=".$in_usage."%%;$warningBit;$criticalBit;0;0 load_Out=".$out_usage."%%;$warningBit;$criticalBit;0;0 traffic_In=%.2f".$in_prefix."b;".$warningBit.";".$criticalBit.";0;0 traffic_Out=%.2f".$out_prefix."b;".$warningBit.";".$criticalBit.";0;0 traffic_in=".$in_perfparse_traffic_str."Bits/s;$warningBit;$criticalBit;0;$speed_card traffic_out=".$out_perfparse_traffic_str."Bits/s;$warningBit;$criticalBit;0;$speed_card \n",$in_traffic,$out_traffic);`

The problem is solved.
