### ISSUE TITLE
Make "keepalive" optional for LMD (livestatus) backend

### ISSUE THREAD

**Issue by smetj** [NagVis/nagvis#124]
Hi,
We have Nagvis connecting to LMD. Since LMD is supposed to be compatible with Livestatus it  works fine for single dashboards.  However, we're not able to render the dashboard overview page unless we turn off 
`keepalive` on the Livestatus connection.

https://github.com/NagVis/nagvis/blob/master/share/server/core/classes/GlobalBackendmklivestatus.php#L245

I guess it would be useful to expose an additional parameter to the `backendtype: mklivestatus` in order to toggle keepalive to on or off

**Comment by marcomusso** [comment]
This seems to be the solution for https://monitoring-portal.org/index.php?thread/41136-nagvis-lmd/

**Comment by LarsMichelsen** [comment]
Sorry for the late response.

I just added the keepalive option to the git. Please check out the nightly build whether or not it works.

I wonder why LMD has not implemented this option or at least silently ignores the option to be compatible with more clients.

I am a bit unsure about the consequences of removing the header. I mean, when you set keepalive=0, this will only skip adding the "KeepAlive: on\n" header. NagVis will not treat the livestatus TCP connection differently at them moment. Maybe it should close the connection after receiving the response, but I am not sure.

**Comment by sni** [comment]
Keepalive should just work with LMD since 1.0.2. I guess this issue can be closed.
-> https://github.com/sni/lmd/commit/8cc3da685110b30356ffb3c690673b4f4c6e380b

**Comment by LarsMichelsen** [comment]
Nice one, Sven! Thanks.

I'll revert my recent NagVis change.
