### ISSUE TITLE
Cloning problem

### ISSUE THREAD

**Issue by eltrasimaco** [NagVis/nagvis#125]
(1.9): When cloning items, the cloned one looses attributes (widths and so) ; in 1.8 it worked correctly.

**Comment by LarsMichelsen** [comment]
What kind of object did you try to clone? Is it a textbox or container object? For these objects you need to klick once for specifying the top/left coordinate of the new object and then move the mouse select the position of the bottom/right coordinate. The position + size are then really not cloned.

If this is not the case, please provide more details.
