### ISSUE TITLE
Worldmap - fetch data from backend

### ISSUE THREAD

**Issue by emoja** [NagVis/nagvis#126]
Hello,
I've successfully configured NagVis to fetch hosts and their coordinates(with LAT and LONG vars)  from my Icinga2 setup using Geomap and livestatus backend. 

Is it possible to do the same with Worldmap?

Thanks

**Comment by LarsMichelsen** [comment]
At the moment it is not possible out of the box. The only source for the coordinates is the worldmap.db, a sqlite database. You could create a mechanism on your own to synchronize the coordinates somehow.
