### ISSUE TITLE
Downtime Centreon is down in Nagvis

### ISSUE THREAD

**Issue by Yeye1997** [NagVis/nagvis#127]
Dear,

I have a problem with Navgis 1.17.10. When I set a downtime on Centreon host, the host is display as downtime in the map but only for one week after that it's displas as if it's down.

Are there settings to change to correct this issue ?

Thank you in advance.

Best regards.

**Comment by LarsMichelsen** [comment]
How do you connect NagVis with Centreon? May be an issue in the backend or data source.

**Comment by LarsMichelsen** [comment]
Closing inactive issue.
