### ISSUE TITLE
Cannot update "General Configuration" with GUI 

### ISSUE THREAD

**Issue by phil0135** [NagVis/nagvis#13]
Hi, 

first of all, thanks for the new version  Nagvis 1.8.2. Looks good.

Unfortunately it is not possible to update the general configuration. 
There is a problem in share/server/core/classes/ViewEditMainCfg.php, because of an invalid index access. 

![nagvis-error](https://cloud.githubusercontent.com/assets/2410400/7163402/0e19de04-e39a-11e4-9b9d-b0457fe1934e.png)

First the code is checking the $_POST variable with prefix 'toggle_', but the actual access is without this prefix.
But even fixing this access problem does not solve the problem because it destroys the config by overwriting the values with 0 or 1.

I have updated my older version of Nagvis, so i am not sure if this affects new installations as well.

Kind regards, 

Philipp Ghirardini

**Comment by LaMi-** [comment]
There seem to be some kind of bug. But your guess is not correct. If you take a look at the dialog, you have two input fields per option. The first one is the checkbox to configure one option or leave it at factory defaults and the second one is the input/dropdown field.

The first field is named toggle_[varname]. The code first checks whether or not this value is set and checked. Then, if the checkbox is checked, it assumes that in this case the value field is available and uses the submitted value [varname] as new value for this option. So using the toggle_[varname] as new value is the wrong approach. We need to know why defaults_hoverchildssort is not part of your POST data.

Could you please send me all POST vars together with their values?

**Comment by phil0135** [comment]
Thanks for the hint. Now I could identify the problem. 

I have a drop down field equal to hoverchildsorder, with the same values ["desc", "asc"]. 

![nagvis-setting](https://cloud.githubusercontent.com/assets/2410400/7175588/a03ad1a4-e416-11e4-809c-4138b0349365.png)

But regarding the comments in the nagvis.ini.php it should be ["s", "a"]. Since I have set this option to "s" manually the box becomes empty and results in the described error. 

Please let me know if it is a general bug or just related to my updated version.

Kind regards, 

Philipp

**Comment by LaMi-** [comment]
Yep, I found this issue too. Check out this commit: https://github.com/NagVis/nagvis/commit/7e1a03be4231d7904cebfbe860bc40523c28c8d8

Please apply this change and re-test it. Hopefully this fixes your issue.
