### ISSUE TITLE
Object service duplicate "Service Name"

### ISSUE THREAD

**Issue by gmourani** [NagVis/nagvis#130]
Hello,

When Adding an object service, the "Service Name" description appears for Host and Service! This make parameter like "label_text" unusable because value like [name] - [service_description] cannot be applied.

Regards,

**Comment by LarsMichelsen** [comment]
Could you please post a screenshot of the unexpected behavior?

Do you use Icinga2 as monitoring core?

**Comment by gmourani** [comment]
Hello,

Attached is a screenshot. You can see that "Service Name" appears two time, one for hostname (not expected) and the second one for service name (expected). I'm using Nagios Core on CentOS 6.9 64bit.

**Comment by gmourani** [comment]
Screenshot again, in case missing in the first reply.

<img width="394" alt="screen shot 2017-10-31 at 2 56 07 pm" src="https://user-images.githubusercontent.com/20328799/32629940-d7295a9c-c568-11e7-9536-9833e592b583.png">

**Comment by LarsMichelsen** [comment]
You mean the label of the hostname row is wrong, right? Just fixed this in git.
