### ISSUE TITLE
Nagvis worldmap - textbox with min_zoom and max_zoom 18 is visible in all zooms

### ISSUE THREAD

**Issue by PepeOnAChair** [NagVis/nagvis#132]
Hello,
it seems that if min_zoom and max_zoom has the same number, the textbox is visible in all zoom levels.

edit: and it I setup the textbox to be visible in 2 or more zoom levels it jumps to different position in every level. It is not locked to one place on the map.
Pep.

**Comment by vpithart** [comment]
I'm going to fix this @LarsMichelsen @PepeOnAChair.
