### ISSUE TITLE
Nagvis 1.8 can't save users/roles changes

### ISSUE THREAD

**Issue by starryl** [NagVis/nagvis#14]
Hello LaMi,

- I am running OMD 1.30, Nagvis 1.8 on Centos 6.6 64bit
- Error "You entered invalid information." - screenshot below
- Error happens when saving any changes on "Manage Users", "Manage Roles"
- I had a look the other thread: https://github.com/NagVis/nagvis/issues/4
- I also read the post at http://www.monitoring-portal.org/wbb/index.php?page=Thread&threadID=32933

Questions: Is this a known bug? If so what is fix? Do I have reinstall/upgrade the whole Nagvis?

Many thanks!
Vince

![image](https://cloud.githubusercontent.com/assets/12513066/7703768/793ae5ea-fe7d-11e4-8f61-055599b9b004.png)

**Comment by LaMi-** [comment]
You should update to the most recent NagVis 1.8-Release. You can find it on nagvis.org.

**Comment by stoney268** [comment]
I have 2 nagvis servers here, both running 1.7.10 and one gives the error the other not. Sure its version related?
