### ISSUE TITLE
Background images "re-zoom" on state updates

### ISSUE THREAD

**Issue by mdetrano** [NagVis/nagvis#140]
When using the zoombar on a map, and a background image on the same map, the image will zoom with each state update of an icon on the map.  If the zoom is "out" , the image keeps getting smaller, and if it's "in" the image keeps growing.  Image will not change when set to normal size.

I experience this in version 1.9.4 of NagVis.

**Comment by LarsMichelsen** [comment]
Just pushed a fix. Will be part of tomorrows daily build and 1.9.5.

**Comment by marcomusso** [comment]
I am experiencing the same problem with 1.9.5. Even at every interval the background image gets bigger (if zoomed in, &zoom=120).

**Comment by marcomusso** [comment]
Seems that just using the browser zoom is a workaround...
