### ISSUE TITLE
PHP 7.2 each() function deprecated

### ISSUE THREAD

**Issue by bcanturk** [NagVis/nagvis#142]
Hi,

First of all, I am using your product almost 10 years. Good job. 

I updated my openSUSE Tumbleweed machine to latest packages which includes PHP. I have encountered a problem after updating PHP packages to PHP 7.2.

```
Error: (0) The each() function is deprecated. This message will be suppressed on further calls
URL: /nagvis/frontend/nagvis-js/index.php
File: /usr/local/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php
Line: 2942
#0 [internal function]: nagvisExceptionErrorHandler(8192, 'The each() func...', '/usr/local/nagv...', 2942, Array)
#1 /usr/local/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(2942): each(Array)
#2 /usr/local/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(985): Dwoo_Compiler->mapParams(Array, Array, 0)
#3 /usr/local/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(668): Dwoo_Compiler->addBlock('topLevelBlock', Array, 0)
#4 /usr/local/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Template/String.php(369): Dwoo_Compiler->compile(Object(Dwoo), Object(Dwoo_Template_File))
#5 /usr/local/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo.php(363): Dwoo_Template_String->getCompiledTemplate(Object(Dwoo), Object(Dwoo_Compiler))
#6 /usr/local/nagvis/share/frontend/nagvis-js/classes/NagVisLoginView.php(76): Dwoo->get(Object(Dwoo_Template_File), Array)
#7 /usr/local/nagvis/share/frontend/nagvis-js/classes/FrontendModLogonDialog.php(48): NagVisLoginView->parse()
#8 /usr/local/nagvis/share/server/core/functions/index.php(120): FrontendModLogonDialog->handleAction()
#9 /usr/local/nagvis/share/frontend/nagvis-js/index.php(53): require('/usr/local/nagv...')
#10 {main}
```

I was using 1.8.5 version, I updated to 1.9.5. Since problem still occurs in 1.9.5, I updated to 1.9.6 but problem still persists.

PHP 7.2.0
Apache/2.4.29

Thanks.

**Comment by dnsmichi** [comment]
dwoo-project/issues/75 has a linked PR.

**Comment by codingwatermelon** [comment]
To whom it may concern, I had to change a few lines with the `each` function in `BASEDIR/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php` and one line in `BASEDIR/share/frontend/nagvis-js/ext/dwoo-1.1.0/plugins/builtin/blocks/if.php` using the code in the linked PR that dnsmichi shared. For instance,

```
while (list($k, $v) = each($params)) {
```

turns into

```
foreach($params as $k => $v) {
```

**Comment by LarsMichelsen** [comment]
Just pushed a change related to this issue. Please confirm the fix using one of the next nightly builds.

**Comment by ksidoine08** [comment]
Hi @LarsMichelsen , I corrected the "while ... each" as indicated but I still have error below

Error: (0) The each() function is deprecated. This message will be suppressed on further calls (/usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/plugins/builtin/blocks/if.php:41)

#0 [internal function]: nagvisExceptionErrorHandler(8192, 'The each() func...', '/usr/share/nagv...', 41, Array)
NagVis#1 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/plugins/builtin/blocks/if.php(41): each(Array)
NagVis#2 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/plugins/builtin/blocks/if.php(170): Dwoo_Plugin_if::replaceKeywords(Array, Object(Dwoo_Compiler))
NagVis#3 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(1058): Dwoo_Plugin_if::postProcessing(Object(Dwoo_Compiler), Array, '', '', '
...')
NagVis#4 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(1330): Dwoo_Compiler->removeBlock('if')
NagVis#5 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(758): Dwoo_Compiler->parse(' NagVis#6 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Template/String.php(369): Dwoo_Compiler->compile(Object(Dwoo), Object(Dwoo_Template_File))
NagVis#7 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo.php(363): Dwoo_Template_String->getCompiledTemplate(Object(Dwoo), Object(Dwoo_Compiler))
NagVis#8 /usr/share/nagvis/share/frontend/nagvis-js/classes/NagVisLoginView.php(85): Dwoo->get(Object(Dwoo_Template_File), Array)
NagVis#9 /usr/share/nagvis/share/frontend/nagvis-js/classes/FrontendModLogonDialog.php(48): NagVisLoginView->parse()
NagVis#10 /usr/share/nagvis/share/server/core/functions/index.php(120): FrontendModLogonDialog->handleAction()
NagVis#11 /usr/share/nagvis/share/frontend/nagvis-js/index.php(57): require('/usr/share/nagv...')
NagVis#12 {main}
