### ISSUE TITLE
Can't use edit mode in normal maps

### ISSUE THREAD

**Issue by rafaelalmeida92** [NagVis/nagvis#146]
Hello guys,
I'm having problem to edit my maps using the nagvis GUI, where I'm trying to edit any objects of any map and when I do the right click on the object doesn't open the properties window of the object.
I've checked another symptom when I try to change the map background and click on save, the configuration is not changed.

If someone get the same problem and solved, please help me.
Regards,

**Comment by nixahnung** [comment]
Same here

**Comment by rafaelalmeida92** [comment]
@nixahnung Thanks to reply me, it's worked for me too, in my case I had some others problems on my Nagvis and I disabled this feature to try solve then, and after solve my problems I forgot that I've changed this configuration.
Regards,
