### ISSUE TITLE
Error when members exist

### ISSUE THREAD

**Issue by rmalta67** [NagVis/nagvis#151]
I've just installed nagvis 1.9.6 and tryied it out.
But I get an error as soon as I login to it.
![image](https://user-images.githubusercontent.com/32720460/37868135-57658e12-2fa2-11e8-9be3-694ab367bcaa.png)
After looking around for a while I came out with this:

- In `NagVisObject.php`, `function getObjectInformation` in the end there is a block creating an array with members if there are any.
- The forach loop gets its object from `getSortedObjectMembers()`
- In the `function getSortedObjectMembers` there is a call to `usort($aTmpMembers, Array("NagVisObject", "sortObjectsByState"));` causing the problem.
- in `function sortObjectsByState($OBJ1, $OBJ2)` there is a call to a non existent function `NagVisObject::sortObjectsByState($state1, $subState1, $state2, $subState2, self::$sSortOrder)`

after changing the call to NagVisObject::**sortStatesByStateValues**($state1, $subState1, $state2, $subState2, self::$sSortOrder) everything is running OK now.

It looks to me as a bug.

**Comment by LarsMichelsen** [comment]
Check out 1.9.7 - it fixes this issue.
