### ISSUE TITLE
NagVis unavailable

### ISSUE THREAD

**Issue by juesor** [NagVis/nagvis#156]
I am getting the following whenever logging into NagVis

It seems that i have the same problem as 

https://github.com/NagVis/nagvis/issues/97

But the fix was not documented.

Error: (0) in_array() expects parameter 2 to be array, boolean given
URL: /nagvis/frontend/nagvis-js/
File: /usr/local/nagvis/share/server/core/classes/GlobalMapCfg.php
Line: 1019
#0 [internal function]: nagvisExceptionErrorHandler(2, 'in_array() expe...', '/usr/local/nagv...', 1019, Array)
#1 /usr/local/nagvis/share/server/core/classes/GlobalMapCfg.php(1019): in_array('worldmap', false)
#2 /usr/local/nagvis/share/server/core/classes/GlobalMapCfg.php(480): GlobalMapCfg->checkMapConfigIsValid()
#3 /usr/local/nagvis/share/frontend/nagvis-js/classes/NagVisHeaderMenu.php(164): GlobalMapCfg->readMapConfig(true)
#4 /usr/local/nagvis/share/frontend/nagvis-js/classes/NagVisHeaderMenu.php(305): NagVisHeaderMenu->getMapList()
#5 /usr/local/nagvis/share/frontend/nagvis-js/classes/NagVisHeaderMenu.php(82): NagVisHeaderMenu->getMacros()
#6 /usr/local/nagvis/share/frontend/nagvis-js/classes/FrontendModOverview.php(77): NagVisHeaderMenu->__toString()
#7 /usr/local/nagvis/share/frontend/nagvis-js/classes/FrontendModOverview.php(55): FrontendModOverview->showViewDialog()
#8 /usr/local/nagvis/share/server/core/functions/index.php(120): FrontendModOverview->handleAction()
#9 /usr/local/nagvis/share/frontend/nagvis-js/index.php(53): require('/usr/local/nagv...')
#10 {main}

**Comment by LarsMichelsen** [comment]
May be related to sources or source parameters in the global section of the map.
