### ISSUE TITLE
Upgrade from Nagvis 1.59 to 1.98 issues

### ISSUE THREAD

**Issue by Christopheric1** [NagVis/nagvis#159]
Hey All,

I am hoping someone can help me out with this really weird issue. I just updated from NagVis 1.59 to 1.98 because I wanted the auto zoom feature that is part of the program starting at Version 1.81 and I figured I would just update it to the latest. 

When changing an existing map, it adds the "define global {" piece to the bottom of the map .cfg and doesn't make a change. I have to manually edit the .cfg for the map to change the iconset, map_image, etc. I have tried creating a new map and the map doesn't even show up. I am not sure how to proceed with this one.

**Comment by LarsMichelsen** [comment]
Can not reproduce this. Closing this very old issue.
