### ISSUE TITLE
Nagvis 1.9.8 install on Ubuntu 18.04

### ISSUE THREAD

**Issue by sziloo** [NagVis/nagvis#161]
Dear Community!

I'm not sure, this is the best place for my topic, but I couldn't find any other Nagvis support forum. Please don't hesitate to recommend me a better one if you think that i'm at the wrong place.
I can't install Nagvis on Ubuntu. I installed the graphviz and sqlite3 packages, so the install.sh script only complains about the missing apache module mod_php. If i run apachectl -M the php7_module is listed, so I think the module is loaded. Do you have any recommendation for solving that kind of problem?

Thank you in advance:

Sz.

**Comment by T100D** [comment]
Hope your answer is here: https://stackoverflow.com/questions/28015896/enabling-mod-php-on-ubuntu

or here:
https://websiteforstudents.com/apache2-with-php-7-1-support-on-ubuntu-18-04-lts-beta-server/

**Comment by wernerfred** [comment]
Hi @sziloo 

What php version are you using?

If you are not sure then run ```php -v``` on the server you are facing this problem and paste the output here :)

**Comment by LarsMichelsen** [comment]
The installer is not detecting the environment correctly. In case one wants to fix this, the install.sh is the right place to look.

Closing this old issue for now.
