### ISSUE TITLE
Without background for map

### ISSUE THREAD

**Issue by alex310579** [NagVis/nagvis#165]
Good afternoon.. I have the version of Nagvis 1.9.7 installed in Centos 7 but I noticed that when I create a new map I can not use a background image that is what I need .. previously the charge from Options / Manage funds, tells me the nagvis that has the image has been loaded but when I create the map it only asks me to id, alias, type of map but not the background that has already been loaded .. could it be that it is badly installed ..?

Greetings..

Centos 7
Server version: Apache/2.4.6 (CentOS)
Server built:   Jun 27 2018 13:48:59
PHP Version => 5.4.16
System => Linux localhost.localdomain 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64
Build Date => Apr 12 2018 19:01:57

**Comment by LarsMichelsen** [comment]
After creating a map you have to edit the map properties and choose the previously uploaded background image there.
