### ISSUE TITLE
Support website is closed

### ISSUE THREAD

**Issue by bphd** [NagVis/nagvis#166]
Precisely, the nginx test page work well !

Also, i asking myself how to get the coordinate from Centreon, that's my demand : 

Hello,

 i've readen that page http://docs.nagvis.org/1.7/en_US/geomap.html who say we can get geocoordinate manully from a CSV file or automaticaly from the backend

My question is if we can do that from the backend ? (maybe i've done something wrong, like misconfigure the backend because i got "The requested feature getGeomapHosts is not provided by the backend (Backend-ID: Central, Backend-Type: centreonbroker). The requested view may not be available using this backend." instead of a geoMap)

If we can't, what the interest of set "backend" here ?

Merci, je peux aussi expliquer en français vu la taille de la communauté !

> New in 1.7.4: It is also possible to set source_type=backend to use the backend set via backend_id to gather the list of hosts to be shown on the geomap and their coordinates. This is only possible when using the livestatus backend. It fetches all hosts from the backend and uses all hosts which have the custom object variables _LAT and _LONG configured. It is possible to filter the fetched hosts by the membership in a host group by setting the option filter_group to the name of the host group.

**Comment by LarsMichelsen** [comment]
Sorry for the late response. The feature needs to be implemented in the backend module.
