### ISSUE TITLE
Changing map does not change URL

### ISSUE THREAD

**Issue by wernerfred** [NagVis/nagvis#168]
### Problem description

Found a weird behaviour using nagvis. When showing the nagvis menu bar and opening a new map trough that menu the new map is opened and the menubar is automatically hidden. But in the url is still the name of the old map. Therefore when then showing the menu bar again the page is reloaded and because of the old map name in the url the old map is rendered.

### Steps to reproduce

1. Open any nagvis map
2. Activate/fade in the nagvis menu bar
3. Use either "open" or the dropdown to open a new map
4. Reload the page (or (de)activate the manu bar again - this will trigger a reload too)

### Expected behaviour

- Reloading the page (no matter if manually or triggered through nagvis) should reload the *actual* page/map

### Current behaviour

- Reloading the page (no matter if manually or triggered through nagvis) will render/load the previous map

### Solution approach

- The current behaviour is clear and understandable due to the fact that opening a new map will not update the url. Therefore the reloading is flawless
- The problem arises while opening a new map. The chosen map will me opened/rendered but the url is not updated

### Version
- Nagvis 1.9.8

_____
Any further information needed?

**Comment by LarsMichelsen** [comment]
Sorry, can not reproduce this. Closing this old issue now.
