### ISSUE TITLE
Multiples distincts geographical maps ?

### ISSUE THREAD

**Issue by mathieuchateau** [NagVis/nagvis#169]
Hello,
I need multiple geographical interactive maps. 
Once one is created, all objects also appears on the other map.

How to have each map with its own objects ?

Using nagvis 1.9.3, sources=worldmap

Regards,

**Comment by LarsMichelsen** [comment]
Sorry, it's not planned at the moment. Should not be too hard to realize by linking different worldmaps  to independent worldmap.db files. But I currently have no plan to realize this.

**Comment by LarsMichelsen** [comment]
Closing this one. It's a duplicate of #139
