### ISSUE TITLE
Nagvis 1.7.10 weathermap lines Issue

### ISSUE THREAD

**Issue by hdep** [NagVis/nagvis#17]
Hello,

I am trying to generate a nagvis weathermap, but I am not able to get the weathermap working. Nagvis report the following error : 

Weathermap Line Error: Missing performance data

I have read the documentation about this : 
http://docs.nagvis.org/1.7/en_US/lines_weathermap_style.html

My plugin seems to be complaint (Byte rate usage)as the output is : 

'in_network'=1003952.54;;;0;125000000 'out_network'=216109.58;;;0;125000000

Have you got any idea ?  Am I missing something ? 

Regards,

**Comment by LaMi-** [comment]
Your performance data format is not supported by the NagVis weathermaps. You should either use a supported plugin or maybe adapt your perfdata keys to in instead of in_network and out instead of out_network.

**Comment by hdep** [comment]
Hello,

thank you, now I got the proper perfdata and it is working.
