### ISSUE TITLE
Weathermap lines --><-- not clickable and no state data

### ISSUE THREAD

**Issue by xkilian** [NagVis/nagvis#170]
When there are multiple Weathermap lines of type ---><--- , some lines are clickable and other are not.
Also when going into edit mode, the contextual menu to edit the object does not appear. Clicking on the lock, will cause it to become editable. Very strange.
Lines with BW do not seem to be affected by this.

Expected behaviour: That all weathermap lines can be interacted with.

Running under Ubuntu 16.04.1, PHP 7.0.30. Nagvis version 1.9.8.

**Comment by xkilian** [comment]
When selecting other Weathermap style lines, as above the line itself sometimes is clickable and sometimes not. The BW or % boxes are always clickable, so it seems to be an issue with the mouseover of the lines themselves.

**Comment by LarsMichelsen** [comment]
This may be related to #173. Closing this for the same reason.
