### ISSUE TITLE
Line Canvas Overlap Issue

### ISSUE THREAD

**Issue by maximest-pierre** [NagVis/nagvis#173]
I recently had the problem that if two lines are put close to each other and diagonally their canvas seems to overlap and were are not able to get the hover widget, nor the link. To fix this I had to move the line horizontally or vertically and everything works.

**Comment by LarsMichelsen** [comment]
Yes, that's an annoying problem with the line rendering logic. Please keep trying to workaround this.

It would need a larger change to fix this. I am not planning to do this. Closing the issue for now.
