### ISSUE TITLE
NagVis 1.9.10 , gadget std_table.php and bad label position

### ISSUE THREAD

**Issue by emi65** [NagVis/nagvis#181]
I use the gadget std_table and I put the label in the right position
I exit from the map and when I came back I find the label in the position 0,0

Here the config information
NagVis Version | 1.9.10
-- | --
PHP Version | 5.4.16
MySQL Version | mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1
OS | Linux sgsvrasnagc01lx.servizi 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

SERVER_SOFTWARE | Apache/2.4.6 (Red Hat Enterprise Linux) PHP/5.4.16
SCRIPT_FILENAME | /opt/nagvis/current/share/frontend/nagvis-js/index.php
SCRIPT_NAME | /nagvis/frontend/nagvis-js/index.php
REQUEST_TIME | 1555412183 (gmdate(): Tue, 16 Apr 2019 10:56:23 +0000)

error_reporting | 30719
safe_mode | no
max_execution_time | 3000 seconds
memory_limit | 128M
loaded modules | Core, date, ereg, libxml,  openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext,  gmp, SPL, iconv, Reflection, session, standard, shmop, SimpleXML,  sockets, mbstring, tokenizer, xml, apache2handler, apfd, bcmath, curl,  dom, fileinfo, gd, gv, json, json_post, exif, mysqlnd, mysql, mysqli,  PDO, pdo_mysql, pdo_sqlite, Phar, posix, propro, raphf, sqlite3, ssh2,  sysvmsg, sysvsem, sysvshm, tidy, wddx, xmlreader, xmlwriter, xsl, http,  zip, mhash
json_encode | Yes
json_decode | Yes

USER_AGENT | Mozilla/5.0 (Windows NT 6.1; rv:65.0) Gecko/20100101 Firefox/65.0

Logon Module | LogonMixed
Auth Module | CoreAuthModSQLite
Authorization Module | CoreAuthorisationModSQLite
Logon Var | REMOTE_USER
REMOTE_USER |  
Logon Create User? | 1
Logon Create User Role? | Guests

User Logged In | admin (1)
User Auth Module | CoreAuthModSQLite
User Logon Module | LogonMixed
User Trusted Auth | No
User Roles | [{"roleId":"1","name":"Administrators"}]
User Permissions | {"*":{"*":{"*":[]}}}

**Comment by LarsMichelsen** [comment]
Sorry, can not reproduce.
