### ISSUE TITLE
ElementHover.js

### ISSUE THREAD

**Issue by bphd** [NagVis/nagvis#183]
I have a question about the hover

It normally has to show "Name of Hostgroup Name (Alias)"

But it shows "Name of Hostgroup Name (Name)"

```html
    <tr><td class="label"><label>[lang_name]</label></td><td>[obj_name][obj_alias_braces]</td></tr>
```

```java
        if(this.obj.conf.alias && this.obj.conf.alias !== '') {
            oMacros.obj_alias        = this.obj.conf.alias;
            oMacros.obj_alias_braces = ' (' +this.obj.conf.alias + ')';
        } else {
            oMacros.obj_alias        = '';
            oMacros.obj_alias_braces = '';
        }
```

How can i show "Name (Alias)" ? (or better, just "Alias")

**Comment by LarsMichelsen** [comment]
I don't understand your problem. 

[lang_name] Is a macro which expands to e.g. "Name of Hostgroup Name (Alias)". You could easily replace this macro with the final text you want to be displayed.

The alias can only be displayed when NagVis receives some for an object.

**Comment by bphd** [comment]
"I don't understand your problem."

"But it shows "Name of Hostgroup Name (Name)" heres one
