### ISSUE TITLE
compatibility with httpd24-httpd Nagvis

### ISSUE THREAD

**Issue by pina-informatico** [NagVis/nagvis#186]
Hello
I have problems when starting Nagvis, since it is ready for Apache (httpd), but not with httpd24-http.
Could you help me?

Regards, and thank you very much

**Comment by v0strik0v** [comment]
Hello !
Same problem for me. Hope nagvis will be updated for Centreon 19.04 and httpd24-http.

**Comment by pina-informatico** [comment]
Hola, al final lo he conseguido, a base de errores y poca información. Te cuento como:
Configurar httpd.conf
Indicamos a apache que acepte la lectura de fincheros index.php:
Editamos el fichero de configuración:

```shell
sudo nano /opt/rh/httpd24/root/etc/httpd/conf/httpd.conf
```
Buscamos esta línea, y tiene que quedar igual:

```shell
    <IfModule dir_module>
        DirectoryIndex index.html index.php
    </IfModule>
```
Incluir modulo de php a la nueva ruta de apache
La instalación de php, se hace en el antiguo directorio de apache, y no en el nuevo.

```shell
sudo cp /etc/httpd/conf.modules.d/*php* /opt/rh/httpd24/root/etc/httpd/conf.modules.d/
```
Incluir las librerias de php

```shell
sudo cp /etc/httpd/modules/libphp* /opt/rh/httpd24/root/etc/httpd/modules/
```
Copiar fichero de conf de php y reiniciamos apache:

```shell
sudo cp /etc/httpd/conf.d/php.conf /opt/rh/httpd24/root/etc/httpd/conf.d/
sudo systemctl restart httpd24-httpd
```
Copiar el fichero de conf de nagvis:

```shell
cp /etc/httpd/conf.d/nagvis.conf /opt/rh/httpd24/root/etc/httpd/conf.d/
```
