### ISSUE TITLE
External URL in rotation pool doesn't work

### ISSUE THREAD

**Issue by swedieman** [NagVis/nagvis#19]
I'm having trouble with viewing an external URL in rotation pools. I get the error: "You are not permitted to access this page (/view/)." (browsing to e.g. "https://localhost/nagvis/frontend/nagvis-js/index.php?mod=Url&act=view&show=http://www.google.com").

When looking at the permissions in the source code I see that they are built up like: [module name]/[action]/[object]. But the URL module classes (like CoreModUrl and FrontendModUrl) do not have a module name. It seems they would need to have the name "Url" and a corresponding permission, like Url/View, for each user role.

Is there any reason why the URL module classes don't have a name?

**Comment by LaMi-** [comment]
Which version?
