### ISSUE TITLE
Error: (0) in_array() expects parameter 2 to be array, boolean given in NagVis

### ISSUE THREAD

**Issue by Yuvaraj89888** [NagVis/nagvis#190]

**Comment by Yuvaraj89888** [comment]
Facing the error while clicking the NagVis in my check_MK where i have created the Network Map

**Comment by LarsMichelsen** [comment]
I have no idea what NagVis, Checkmk or PHP version you are using.

But I guess this is an incompatibility of the NagVis version you are using with the PHP version of your server. Updating to last Checkmk stable release should fix the issue because it ships with a newer NagVis version.

**Comment by Yuvaraj89888** [comment]
Hi Lars ,
My actual issue is while editing the map suddenly the page was throwing the following error.
Error: (0) in_array() expects parameter 2 to be array, boolean given
URL: /tester/nagvis/frontend/nagvis-js/index.php
File: /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php
Line: 1019
#0 [internal function]: nagvisExceptionErrorHandler(2, 'in_array() expe...', '/opt/omd/versio...', 1019, Array)
#1 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php(1019): in_array('worldmap', false)
#2 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php(480): GlobalMapCfg->checkMapConfigIsValid()
#3 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/classes/NagVisHeaderMenu.php(164): GlobalMapCfg->readMapConfig(true)
#4 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/classes/NagVisHeaderMenu.php(305): NagVisHeaderMenu->getMapList()
#5 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/classes/NagVisHeaderMenu.php(82): NagVisHeaderMenu->getMacros()
#6 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/classes/FrontendModOverview.php(77): NagVisHeaderMenu->__toString()
#7 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/classes/FrontendModOverview.php(55): FrontendModOverview->showViewDialog()
#8 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/server/core/functions/index.php(120): FrontendModOverview->handleAction()
#9 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/index.php(53): require('/opt/omd/versio...')
#10 {main}
