### ISSUE TITLE
Map status recursivity

### ISSUE THREAD

**Issue by NotAProfessionalDeveloper** [NagVis/nagvis#194]
Example:
Map A contains link to Map B
Map B contains link to Map A

If Map A has an aggregate state of "Warning" for example, then the link on Map A toward Map B will also be in state "Warning". This is because Map B contains a link back to Map A which is in state "Warning" and therefore the aggregate state of Map B becomes "Warning".

In case of maps being linked recursively like: Map A --(1)--> Map B --(2)--> Map A
Link (1) should only consider the aggregate status of Map B _excluding_ link (2) (the link back to Map A).

This should also hold true at any depth (e.g. A -> B -> C -> A etc.)

The practical problem here is: If you have a map rotation where each map contains a link to all other maps (just to see the status of the other maps while they're not being displayed), all maps take the state of the "worst" map, which is obviously unproductive.

**Comment by LarsMichelsen** [comment]
Do you experience a bug here? If so, please also post some screenshots to illustrate the issue.

**Comment by NotAProfessionalDeveloper** [comment]
I'm not sure if this is a bug. But it should be discussed. 

The screenshot I have attached was taken on the "core" map.

You see that the summary state of the link to the "servers" map includes the state of the "core" map we're at (because the "servers" map contains a map link back to the "core" map).

The link to the "servers" map shows state "critical(acknowledged)" because (among others) the core map is in that state.

As a matter of fact the "core" map is in that state because the "servers" map is in that state, because the "core" map is in that state etc.

See where I'm going?

The recursivity should be stopped somewhere. Preferably at the start / the first duplicate found down the path.

![image](https://user-images.githubusercontent.com/277893/59867026-522f1580-938d-11e9-8f44-bd513cb75e51.png)

**Comment by NotAProfessionalDeveloper** [comment]
Maybe a simple and convenient fix would be to exclude a linked map from the summary state of the parent map.

**Comment by NotAProfessionalDeveloper** [comment]
I will be proposing to not consider the state of the child object in the summary state of the current object if it is a map, and the child object also is a map.

However, I don't know how maps have actually been designed to be used. Maybe the initial thought was that a map only ever contains another map containing child objects of the parent map (to implement "drill-down"-style maps). In that case there would rarely be a map link back from the child to the parent map. In that case my proposal may generate a non-expected behavior (since the parent no longer turns critical if one of the childs is critical). However we could make this a configurable parameter somehow?

**Comment by LarsMichelsen** [comment]
We could only merge this if a) it was configurable and b) the default behavior was the same as before. Even better would be to have a clean loop detection.

**Comment by NotAProfessionalDeveloper** [comment]
A viable **workaround** for what I am doing is to display the tree view (sidebar) in our NOC view. That way we do not need to add a map link to every other map in each map, which was quite a stupid way anyway. The tree view is set up to correspond to the map rotation so we see all we need to see.

Which does not mean that there is nothing to be fixed. I'll update my pull request with at least a configurable setting.
