### ISSUE TITLE
NagVis Configuration for NGINX

### ISSUE THREAD

**Issue by djengineerllc** [NagVis/nagvis#2]
Hello, I was wondering if anyone could help out with a configuration that would work with NGINX.  I can't seem to get it working correctly.  I got nagios and pnp4nagios working with NGINX, and NagVis is the last thing left on my list.

**Comment by LaMi-** [comment]
What is your exact problem with NGINX? Did you try to configure NagVis with it?

**Comment by djengineerllc** [comment]
Thanks for your response.  I did try to configure NagVis, but it seems that the authentication is acting weird since I've changed from apache to nginx.  I have been just playing around with trying to get it to work.  I'm not the best with the NGINX syntax.  This is what I got so far:
```
server {
    server_name serverHostName.com;
    access_log /var/log/nginx/nagvis-access.log;
    error_log /var/log/nginx/nagvis-error.log;
    auth_basic "Private";
    auth_basic_user_file /usr/local/nagios/etc/htpasswd.users;
    index index.php index.html;
    location /nagvis {
        alias /usr/local/nagvis/share;
    }
    location ~ ^/nagvis/(.*\.php)$ {
        alias /usr/local/nagvis/share/$1;
        include /etc/nginx/fastcgi_params;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
    }
}
```

NOTES:
1 - 
I was trying to use the same basic authentication that nagios uses, so that is why the auth_basic_user_file is pointing to "/usr/local/nagios/etc/htpasswd.users" instead of something like "/usr/local/nagvis/htpasswd.users".
2 - 
I have nagvis directory at /usr/local/nagvis.

Issues:
Not sure if this is an issue or not but when I go to http://serverHostName.com/nagvis/, I get redirected to http://serverHostName.com/nagvis/frontend/nagvis-js/index.php

So I just ignored that.  Then I try to login, but it is authenticating with NagVis form instead of using basic authentication popup.

So I didn't know if there is something I don't have configured correctly.

This is what I had configured in Apache:

```
Alias /nagvis "/usr/share/nagvis/share/"

<Directory "/usr/share/nagvis/share/">
  Options FollowSymLinks
  AllowOverride None
  Order allow,deny
  Allow from all
  #Require all granted


  # To enable Nagios basic auth on NagVis use the following options
  # Just uncomment it. Maybe you need to adjust the path to the
  # Auth user file.
  #
  # If you use the NagVis internal auth mechanism based on the web
  # for you won't need this.
  #
  AuthName "NagVis Access"
  AuthType Basic
  AuthUserFile /usr/local/nagios/etc/htpasswd.users
  Require valid-user

  # With installed and enabled mod_rewrite there are several redirections
  # available to fix deprecated and/or wrong urls. None of those rules is
  # mandatory to get NagVis working.
  <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /nagvis

    # Use mod_rewrite for old url redirection even if there are php files which
    # redirect the queries itselfs. In some cases the mod_rewrite redirect
    # is better than the php redirect.
    #
    # Using the php redirect seems to be better in some cases where https/http servers
    # are mixed. For example in OMD setups where using apache own mode and https in the
    # frontend and http in the backend apache servers.
    #
    # Disabling this redirect by default in the hope that the php direct works better.
    #RewriteCond %{REQUEST_URI} ^/nagvis(/config\.php|/index\.php|/|)(\?.*|)$
    #RewriteRule ^(.*)$ /nagvis/frontend/nagvis-js/%1%2 [R=301,L]

    # Redirect old regular map links
    RewriteCond %{REQUEST_URI} ^/nagvis/frontend/(wui|nagvis-js)
    RewriteCond %{QUERY_STRING} map=(.*)
    RewriteRule ^(.*)$ /nagvis/frontend/nagvis-js/index.php?mod=Map&act=view&show=%1 [R=301,L]

    # Without map= param
    RewriteCond %{REQUEST_URI} ^/nagvis/frontend(/wui)?/?(index.php)?$
    RewriteRule ^(.*)$ /nagvis/frontend/nagvis-js/index.php [R=301,L]

    # Redirect old rotation calls
    RewriteCond %{REQUEST_URI} ^/nagvis/frontend/nagvis-js
    RewriteCond %{QUERY_STRING} !mod
    RewriteCond %{QUERY_STRING} rotation=(.*)
    RewriteRule ^(.*)$ /nagvis/frontend/nagvis-js/index.php?mod=Rotation&act=view&show=%1 [R=301,L]
  </IfModule>
</Directory>
```

Dangit!!!
I just figured it out, lol.

I was using /usr/share/nagvis/share/ in Apache and /usr/local/nagvis/share/ in NGINX.
Once I updated NGINX with the correct path it worked, lol.

OK, sorry for the troubles!

**Comment by LaMi-** [comment]
Ist this nginx snippet the final working version? I would like to include an example config snippet in the repo for other nginx users.

**Comment by sistemmsn** [comment]
Hi how are things?

I have tried to configure nagvis with nginx, but if any success the result in the end is 403 Forbidden and 404

Anyone who can support?
