### ISSUE TITLE
Fails after install (can't pull on any of the initial config.php or index.php)

### ISSUE THREAD

**Issue by tbeisigl** [NagVis/nagvis#208]
Hello, I am new to nagvis and upon installing it, it completed. I attempted to pull up the initial index.php to make sure it got so far as to at least serving out that, but it is spewing out code errors about the tmpl/compile folder needing to be writable. I have confirmed that the folder is not only writable, but made the change to make it rwx by all just to test.

I am running the following versions:
CentOS7.6
Apache 2.4.6
PHP 5.4
Graphviz 2.30.1
SQLite 3.7
and Nagios 4.1.1

This is the error I am seeing. Any pointers on where to go from here? 

Error (Dwoo_Exception): The compile directory must be writable, chmod "/usr/local/nagvis/var/tmpl/compile/" to make it writablearray(1) { [0]=> array(2) { ["function"]=> string(15) "nagvisException" ["args"]=> array(1) { [0]=> object(Dwoo_Exception)#17 (7) { ["message":protected]=> string(103) "The compile directory must be writable, chmod "/usr/local/nagvis/var/tmpl/compile/" to make it writable" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(66) "/usr/local/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo.php" ["line":protected]=> int(686) ["trace":"Exception":private]=> array(5) { [0]=> array(6) { ["file"]=> string(66) "/usr/local/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo.php" ["line"]=> int(258) ["function"]=> string(13) "setCompileDir" ["class"]=> string(4) "Dwoo" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> string(34) "/usr/local/nagvis/var/tmpl/compile" } } [1]=> array(6) { ["file"]=> string(77) "/usr/local/nagvis/share/frontend/nagvis-js/classes/FrontendTemplateSystem.php" ["line"]=> int(37) ["function"]=> string(11) "__construct" ["class"]=> string(4) "Dwoo" ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> string(34) "/usr/local/nagvis/var/tmpl/compile" [1]=> string(32) "/usr/local/nagvis/var/tmpl/cache" } } [2]=> array(6) { ["file"]=> string(71) "/usr/local/nagvis/share/frontend/nagvis-js/classes/NagVisHeaderMenu.php" ["line"]=> int(48) ["function"]=> string(11) "__construct" ["class"]=> string(22) "FrontendTemplateSystem" ["type"]=> string(2) "->" ["args"]=> array(0) { } } [3]=> array(6) { ["file"]=> string(64) "/usr/local/nagvis/share/frontend/nagvis-js/classes/ViewError.php" ["line"]=> int(50) ["function"]=> string(11) "__construct" ["class"]=> string(16) "NagVisHeaderMenu" ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> string(7) "default" [1]=> NULL } } [4]=> array(6) { ["file"]=> string(52) "/usr/local/nagvis/share/frontend/nagvis-js/index.php" ["line"]=> int(61) ["function"]=> string(5) "parse" ["class"]=> string(9) "ViewError" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> object(NagVisException)#14 (8) { ["message":protected]=> string(120) "Unable to open auth database (sqlite:/usr/local/nagvis/etc/auth.db): "SQLSTATE[HY000] [14] unable to open database file"" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(62) "/usr/local/nagvis/share/server/core/classes/CoreAuthModPDO.php" ["line":protected]=> int(57) ["trace":"Exception":private]=> array(3) { [0]=> array(6) { ["file"]=> string(63) "/usr/local/nagvis/share/server/core/classes/CoreAuthHandler.php" ["line"]=> int(47) ["function"]=> string(11) "__construct" ["class"]=> string(14) "CoreAuthModPDO" ["type"]=> string(2) "->" ["args"]=> array(0) { } } [1]=> array(6) { ["file"]=> string(55) "/usr/local/nagvis/share/server/core/functions/index.php" ["line"]=> int(44) ["function"]=> string(11) "__construct" ["class"]=> string(15) "CoreAuthHandler" ["type"]=> string(2) "->" ["args"]=> array(0) { } } [2]=> array(4) { ["file"]=> string(52) "/usr/local/nagvis/share/frontend/nagvis-js/index.php" ["line"]=> int(53) ["args"]=> array(1) { [0]=> string(55) "/usr/local/nagvis/share/server/core/functions/index.php" } ["function"]=> string(7) "require" } } ["previous":"Exception":private]=> NULL ["e"]=> array(3) { ["message"]=> string(120) "Unable to open auth database (sqlite:/usr/local/nagvis/etc/auth.db): "SQLSTATE[HY000] [14] unable to open database file"" ["title"]=> string(5) "ERROR" ["type"]=> string(5) "error" } } } } } ["previous":"Exception":private]=> NULL } } } }

**Comment by T100D** [comment]
Did you check on the owner settings of the file or folder, should be something like apache:apache at least it is in Centos 6.X.

**Comment by LarsMichelsen** [comment]
Sorry, cannot answer this kind of question here.
