### ISSUE TITLE
INVALID CHAR in NagVisCompressed.js

### ISSUE THREAD

**Issue by gabortakacs78** [NagVis/nagvis#209]
Hi,

It looks there is a problem with v1.9.14 and Internet Explorer 11.
After update our NagVis, none of the maps (nor NagVis menu) didn't worked anymore in IE11!!!
Other browsers were OK...

After some debugging, I found the following error in IE Development Tools:
Invalid Chars in NagVisCompressed.js (Row 4631, Column 23)

Once I changed all GRAVE ACCENT ( \` ) chars in file, it worked again:

nagios@iumg136> diff NagVisCompressed.js.orig nagvis-js/js/NagVisCompressed.js

< ltp[0].style.filter = \`saturate(${saturate_percentage}%)\`
\> ltp[0].style.filter ='saturate(${saturate_percentage}%)'

< window.location.hash = \`${new_center.lng}/${new_center.lat}/${g_map.getZoom()}\`;
\> window.location.hash = '${new_center.lng}/${new_center.lat}/${g_map.getZoom()}';

I guess this problem is related to: TEMPLATE LITERALS ARE NOT SUPPORTED BY IE11
For example:
https://stackoverflow.com/questions/43048455/ie11-throwing-script1014-invalid-character-where-all-other-browsers-work
https://caniuse.com/#search=%60
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

I have checked, and this file "nagvis-1.9.14/share/frontend/nagvis-js/js/NagVisCompressed.js" doesn't exist in SOURCE CODE, so I guess it has been created during installation...

Could you please check and fix it if possible, as we still have so many computers with Internet Explorer 11!

Thanks in advance!

Br,
Gabor Takacs
AUDI Monitoring Team

**Comment by T100D** [comment]
Might be related to this: https://github.com/NagVis/nagvis/issues/204

**Comment by gabortakacs78** [comment]
Super, Thx!
