### ISSUE TITLE
sfdp overlap=prism Patch 

### ISSUE THREAD

**Issue by kkurzyk** [NagVis/nagvis#21]
1) automap.patch
--- /tmp/version/automap.php	2015-09-11 11:03:58.649508091 +0200
+++ share/server/core/sources/automap.php	2015-09-11 11:05:26.905505036 +0200
@@ -65,6 +65,7 @@
         'compress' => l('compress'),
         'ipsep'    => l('ipsep'),
         'vpsc'     => l('vpsc'),
+        'prism'    => l('prism'),
     );
 }
 
2) matches.patch
--- /tmp/version/matches.php	2015-09-11 11:04:05.269507862 +0200
+++ share/server/core/defines/matches.php	2015-09-11 11:04:32.097506933 +0200
@@ -84,7 +84,7 @@
 define('MATCH_OBJECT_TYPES', '/^(host|service|hostgroup|servicegroup|dyngroup|aggr|map)$/');
 define('MATCH_AUTOMAP_RENDER_MODE', '/^(directed|undirected|radial|circular|undirected2|undirected3)?$/');
 define('MATCH_AUTOMAP_RANKDIR', '/^(TB|LR|BT|RL)?$/');
-define('MATCH_AUTOMAP_OVERLAP', '/^(true|false|scale|scalexy|ortho|orthoxy|orthoyx|compress|ipsep|vpsc)?$/');
+define('MATCH_AUTOMAP_OVERLAP', '/^(true|false|scale|scalexy|ortho|orthoxy|orthoyx|compress|ipsep|vpsc|prism)?$/');
 define('MATCH_AUTOMAP_BUSINESS_IMPACT', '/^(0_development|1_testing|2_standard|3_production|4_top_production|5_business_critical)?$/');
 define('MATCH_AUTOMAP_HOSTNAME', '/^[0-9a-zа-яё\p{L}:+[\]()_.,\-?!#@=\/\\\<>]+$/iu');
 define('MATCH_LINE_TYPE', '/^(10|11|12|13|14|15)?$/');

**Comment by LaMi-** [comment]
Applied it, thanks
