### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by CuentaAxion** [NagVis/nagvis#211]
I have an error in nagvis which I have 326 maps added and if I want to assign a role to a user and then a map with read only it allows me but if I add a new map and I have 327 maps it does not let me assign and I do not get any error but only my nagvis is blocked, not because of the capacity or because nagvis is overloaded ...

Thanks you

**Comment by LarsMichelsen** [comment]
Sorry, can not answer this kind of questions here.
