### ISSUE TITLE
Suddenly:  Error (BackendConnectionProblem): The backend with the...

### ISSUE THREAD

**Issue by berilslv** [NagVis/nagvis#212]
Hi guys,

I hope somebody can help me regarding nagvis! I just marked one tick header_menu/hover_menu , and boom, suddenly im getting error:
https://pastebin.com/vDZdFJLa

I dont know from where to start initalize problem, because in logs, there is noly User XXX has logged in, and thats it.
Nagvis version: https://imgur.com/a/NZFrpKG

Is there any easy way how to reset nagvis to default's without changing config file etc. ?
Thanks in advance!

**Comment by LarsMichelsen** [comment]
Looks like there is an object in your configuration referencing to an empty backend_id (Error: The backend with the id "" is not defined.).
