### ISSUE TITLE
Javascript Error: Node was not found

### ISSUE THREAD

**Issue by AshCarhart93** [NagVis/nagvis#220]
![image](https://user-images.githubusercontent.com/57763509/68870165-59ffa580-06f2-11ea-8b60-a738aa888a94.png)

Hi All, After updaing Nagvis to v1.9.17 I'm getting the above error anytime I try to edit any maps? Can anyone advice on a fix? It doesnt seem to affect my default "home" map.

Version Information
--
NagVis Version | 1.9.17
PHP Version | 7.3.11
MySQL Version |  
OS | Linux  [[SERVER NAME]] 3.10.0-1062.1.1.el7.x86_64 #1 SMP  Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

SERVER_SOFTWARE | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.11
SCRIPT_FILENAME | /usr/local/nagvis/share/frontend/nagvis-js/index.php
SCRIPT_NAME | /nagvis/frontend/nagvis-js/index.php
REQUEST_TIME | 1573744994 (gmdate(): Thu, 14 Nov 2019 15:23:14 +0000)

error_reporting | 30719
safe_mode | no
max_execution_time | 30 seconds
memory_limit | 128M
loaded modules | Core, date, libxml,  openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard,  apache2handler, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant,  mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, interbase, intl,  json, ldap, exif, mysqlnd, odbc, PDO, pgsql, Phar, posix, pspell,  recode, shmop, SimpleXML, snmp, soap, sockets, sodium, sqlite3, sysvmsg,  sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, zip, mysqli,  pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite,  wddx, xmlreader, xmlrpc, amqp, apcu, geoip, igbinary, imagick, lzf,  msgpack, smbclient, yaml, memcached, mongodb, redis, libsmbclient, Zend  OPcache, xdebug
json_encode | Yes
json_decode | Yes

USER_AGENT | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0

Logon Module | LogonMixed
Auth Module | CoreAuthModSQLite
Authorization Module | CoreAuthorisationModSQLite
Logon Var | REMOTE_USER
REMOTE_USER |  
Logon Create User? | 1
Logon Create User Role? | Guests

User Logged In | acarhart (8)
User Auth Module | CoreAuthModSQLite
User Logon Module | LogonMixed
User Trusted Auth | No
User Roles | [{"roleId":"1","name":"Administrators"}]
User Permissions | {"*":{"*":{"*":[]}}}

**Comment by T100D** [comment]
Can you check the last line in the map that goes wrong, looks like a similar issue we have on a busy server that corrupts maps on editing. The last line is an empty one, deleting the line solves our problem, if the file has not gone totally blank.

**Comment by AshCarhart93** [comment]
> 
> 
> Can you check the last line in the map that goes wrong, looks like a similar issue we have on a busy server that corrupts maps on editing. The last line is an empty one, deleting the line solves our problem, if the file has not gone totally blank.

Not quite the resolution but you pointed be in the right direction. Looks like in the copy during the file upgrade some maps have become corrupt. Copying and pasting the contents into a new file seems to fix the problem. Alot of maps to go through and check now however.

Thanks :)

**Comment by AshCarhart93** [comment]
Scratch that it was definitely the two blank lines at the bottom of the configs. @T100D thanks again!

**Comment by T100D** [comment]
Your welcome, this still might point to an error in file handling.

**Comment by AshCarhart93** [comment]
Thanks also found the issue was appearing when I had Hover URLS on some of the Maps. Do we know if this function is still working in this version or is it likely due to where my html files are located and how i've defined them them in the apache config?

**Comment by T100D** [comment]
That is strange, the maps should normally only be read when loaded.

Things you could look at:
 - SELINUX  (it's disabled here)
 - give PHP memory a bump to 256M and see what happens.
 - Is editing enabled all the time in nagvis?
 - is some kind of caching active in apache, we had errors due to caching in the past?

Our files are in /usr/local/nagvis, if you have it installed with their script I guess everything else is fine.
