### ISSUE TITLE
Incorrect Grafana iframe display on hover

### ISSUE THREAD

**Issue by p4k8** [NagVis/nagvis#229]
Expected behaviour:
With `hover_url` on host or service object set to panel iframe URL (similar to `http://play.grafana.org/d-solo/000000012/grafana-play-home?orgId=1&from=1575808514878&to=1575815714878&panelId=2` from play.grafana.org) a panel from grafana should be displayed on hover.

Problem:
On hover iframe with following error message is displayed:
>     If you're seeing this Grafana has failed to load its application files
>     This could be caused by your reverse proxy settings.
>     If you host grafana under subpath make sure your grafana.ini root_path setting includes subpath
>     If you have a local dev build make sure you build frontend using: npm run dev, npm run watch, or npm run build
>     Sometimes restarting grafana-server can help
Embedding iframe with same panels in map as an iframe container displays panel correctly.

Setup:
NagVis 1.9.14, Grafana 6.3
NagVis is served with Apache. Grafana has Nginx in front, proxying from 80 to 3000 without subpath.
Both Apache and Nginx were configured with permissible CORS headers (as in https://enable-cors.org/server_apache.html and https://enable-cors.org/server_nginx.html respectively)

**Comment by LarsMichelsen** [comment]
You may have to add some custom hover template that contains an iframe tag pointing to the URL of your choice.
