### ISSUE TITLE
Nagvis 1.7 with icinga 2.3.8

### ISSUE THREAD

**Issue by denbekker** [NagVis/nagvis#23]
Hello,

Im trying to install nagvis with Icinga2. Everything is running. The only problem I'm having is that when I create a map, the Icons are all blue.. with the error message :
- Problem (Backend: live_2) The Object "xxx" does not exist (servicegroupMemberstate). When I refresh the Icon, it works. After a certain time it becomes blue again. Also when I click on the Icon i'm seeing the servicegroups in icinga2..

In icinga2 I activated the livestatus feature:

object LivestatusListener "livestatus-tcp" { 
  socket_type = "tcp"
  bind_port = "127.0.0.1"
  bind_port = "6558"
}

object LivestatusListener "livestatus-unix" {
  socket_type = "unix"
  socket_path = "/var/run/icinga2/cmd/livestatus"
}

The nagvis config for the backend looks like this:

[backend_live_2]
backendtype="mklivestatus"
socket="tcp:127.0.0.1:6558"
htmlcgi="/icingaweb2/monitoring"
timeout=30

Im running the following config:
Nagvis: 1.7.10
Distro: Debian 7.8
Apache: 2.2.22
PHP: 5.4.39

Does anyone have a clue what I can do to solve this problem ??

Cheers,

- Pascal

**Comment by LaMi-** [comment]
Maybe you should try using the current NagVis 1.8 release.
