### ISSUE TITLE
Issue with interactive map

### ISSUE THREAD

**Issue by bitboy85** [NagVis/nagvis#235]
i'm using the current stable version of nagvis on rpi with icinga2 installed.
If i create a new interactive map and open it two errors appear:

`Unable to open worldmap database (sqlite:/usr/share/icinga2/nagvis/etc/worldmap.db): "could not find driver"`

and if i close this message a second one shows up:

`Javascript error occured: NotFoundError: Node was not found https://icinga/nagvis/frontend/nagvis-js/js/NagVisCompressed.js?v=1.9.17 (1799)`

The tiles from osm are loaded and i'm able to zoom and move the map around

**Comment by T100D** [comment]
Is sqlite and/or qt-sqlite installed on your system?

**Comment by bitboy85** [comment]
Hi,
thx for answer. I installed sqlite3 and after this i got a different error because the database had wrong permissions.

Maybe the install script of a future version could check if the packages are installed?

This solved the issue:
```
sudo apt-get install php-sqlite3 sqlite3

sudo chown www-data:www-data /usr/share/icinga2/nagvis/etc/worldmap.db

sudo service apache2 restart
```

**Comment by LarsMichelsen** [comment]
Feel free to send us pull requests for the installer.
