### ISSUE TITLE
Feature request: weathermap circuit "down" color adjustment

### ISSUE THREAD

**Issue by ekrichbaum** [NagVis/nagvis#236]
When a weathermap line (type 13 in this case but would apply to type 14/15?), color should be the same as line type 1 down (Red).

![weathermap](https://user-images.githubusercontent.com/11653069/72085397-d9f95480-32ca-11ea-8f62-adf3261322c5.png)

**Comment by ekrichbaum** [comment]
Seems to be hardcoded in this function of NagVisCompressed.js
`
calcWeathermapColor: function(id) {
if (this.obj.conf.summary_state == "ERROR")
return oStates["ERROR"].color;
if (!this.perfdata)
return '#FFCC66';
if (this.perfdata[id][2] == '%' && this.perfdata[id][1] !== null) {
return this.getColorFill(this.perfdata[id][1]);
} else {
this.obj.conf.summary_output += ' (Weathermap Line Error: Value '
+ id +' is not a percentage value)';
return oStates["ERROR"].color;
}
},
`

Can be fixed by hardcoding but maybe should just be  oStates["CRITICAL"].color (instead of ERROR.

**Comment by ekrichbaum** [comment]
oh, BTW, that and the function above it are duplicated in ElementLine.js so not sure the difference between the two.

**Comment by ekrichbaum** [comment]
#243

**Comment by LarsMichelsen** [comment]
Fixed by merging #243.
