### ISSUE TITLE
nagvis not working after upgrading from 1.9.8

### ISSUE THREAD

**Issue by gelete5198** [NagVis/nagvis#237]
I'm having problems trying to update from 1.9.8 to any version. I tried updating to 1.9.17 and to 1.9.10 and in both cases I get 500 error after upgrade. Anybody had same problem before?. After trying update I make a downgrade to 1.9.8 again and all is working fine. My php version is 5.3.3

Please help

**Comment by ekrichbaum** [comment]
Did you see what the error was? You may want to upgrade to php 7 and try again.  5.3 stopped being support (in general, not specifically nagvis) last year. https://www.php.net/eol.php

**Comment by gelete5198** [comment]
Thanks for your answer!!!!

Any guide to how to upgrade php?. Will php upgrade affect to nagios xi installation?

Thanks!

**Comment by ekrichbaum** [comment]
I couldn't begin to guess what other software you have on the box to answer that question.  If the other software is current you shouldn't have issues but homebrewed scripts etc, could.

The method would depend on your platform (apt, yum, dnf) along with other updates (libraries/extensions/kernel/ssh/ssl).   All distros have some method of update until you hit a point where they are out of level as well, then a larger upgrade process would be needed.  The other possibility is manually compiling.

**Comment by gelete5198** [comment]
Hi again!,

After upgrading to php 7 I'm still having same problem. I tried to upgrade to nagvis 1.9.9 an 1.9.10 and is not working (same error http 500).

Is there any specific log where I could check possible errors?

**Comment by ekrichbaum** [comment]
check your apache/webserver log.  The location will depend on your version of linux.  /var/log/httpd/ or something similar.  You may be missing a required library for the software,  Check out http://nagvis.org/support for information on support itself.  Did the installer give you any information when it was run?  The install log should have checked for those types of problems.

+--- Checking prerequisites ---------------------------------------------------+
| PHP 7.3                                                                found |
|   PHP Module: gd php                                                   found |
|   PHP Module: mbstring php                                             found |
|   PHP Module: gettext compiled_in                                      found |
|   PHP Module: session compiled_in                                      found |
|   PHP Module: xml php                                                  found |
|   PHP Module: pdo php                                                  found |
|   Apache mod_php                                                       found |
| Graphviz 2.40                                                          found |
|   Graphviz Module dot 2.40.1                                           found |
|   Graphviz Module neato 2.40.1                                         found |
|   Graphviz Module twopi 2.40.1                                         found |
|   Graphviz Module circo 2.40.1                                         found |
|   Graphviz Module fdp 2.40.1                                           found |
| WARNING: The SQLite package was not found.                                   |
|          This may not be a problem if you installed it from source           |

**Comment by gelete5198** [comment]
Seems that I found what was happening. Checking ssl_error_log file could see how an error was appearing every time I tried to access to nagvis. Error was related with a file not found (CoreLogonSession.php). After copy this file from a backup nagvis started running again. Seems that every time I tried to update nagvis, this file was deleted I don't know why
