### ISSUE TITLE
Geomaps dont work

### ISSUE THREAD

**Issue by iangandon** [NagVis/nagvis#238]
Anytime i try to generate a new geomap within nagvis the map renders with a cant load tile background. The points are actually plotted however. This is using nagvis 1.9.17

Browsing to http://geomap.nagvis.org/ and clicking on the majority of the URL's can generate an example of this phenomenon. 

Bit of investigating appears to show that the api is no longer valid according to openstreetmap. see https://wiki.openstreetmap.org/wiki/Static_map_images. 

Are there any plans to migrate this to the google functionality mentioned on the openstreetmap page?

I can see the worldmap has been moved to  (https://{s}.tile.openstreetmap.org/)

**Comment by LarsMichelsen** [comment]
Issue has been solved. You may have to remove the locally cached wrong tiles from your installation.
