### ISSUE TITLE
Invalid JSON response

### ISSUE THREAD

**Issue by asiergda** [NagVis/nagvis#239]
Hi,
after fresh install when adding a new host/service/...an error is shown:
Invalid JSON response

Version Information
--
NagVis Version | 1.9.17
PHP Version | 7.3.11-0ubuntu0.19.10.3
MySQL Version | mysql  Ver 8.0.19-0ubuntu0.19.10.3 for Linux on x86_64 ((Ubuntu))
OS | Linux management-station 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

SERVER_SOFTWARE | Apache/2.4.41 (Ubuntu)
SCRIPT_FILENAME | /usr/local/nagvis/share/frontend/nagvis-js/index.php
SCRIPT_NAME | /nagvis/frontend/nagvis-js/index.php
REQUEST_TIME | 1582302683 (gmdate(): Fri, 21 Feb 2020 16:31:23 +0000)

error_reporting | 30719
safe_mode | no
max_execution_time | 30 seconds
memory_limit | 128M
loaded modules | Core, date, libxml,  openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session,  standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, dom,  mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli,  pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets,  sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader,  xmlwriter, xsl, Zend OPcache
json_encode | Yes
json_decode | Yes

USER_AGENT | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

Logon Module | LogonMixed
Auth Module | CoreAuthModSQLite
Authorization Module | CoreAuthorisationModSQLite
Logon Var | REMOTE_USER
REMOTE_USER |  
Logon Create User? | 1
Logon Create User Role? | Guests

User Logged In | admin (1)
User Auth Module | CoreAuthModSQLite
User Logon Module | LogonMixed
User Trusted Auth | No
User Roles | [{"roleId":"1","name":"Administrators"}]
User Permissions | {"*":{"*":{"*":[]}}}

**Comment by ekrichbaum** [comment]
can you give a little more info, please? What type of a map are you trying to add an item to? Do you have sqlite installed?

Can you log in and view the demo items?

**Comment by LarsMichelsen** [comment]
No response for a month, closing.
