### ISSUE TITLE
Swap issue using Nagvis

### ISSUE THREAD

**Issue by fabienclerc** [NagVis/nagvis#24]
Hello,

I'm using Nagios 4.0.8 on a redhat server

[nagios@lx01954d ~]$ uname -a
Linux lx01954d 2.6.18-194.32.1.el5 #1 SMP Mon Dec 20 10:52:42 EST 2010 x86_64 x86_64 x86_64 GNU/Linux

I face no issue with it

Now, I've installed Nagvis 1.8.5 with mk-livestatus-1.2.6p12 and I activated Nagvis.
Nagvis works for an half hour but the swap raised and finally, the server freeze and need the VMware rebooted.

Do you have any idea about this issue ?

Regards

**Comment by LaMi-** [comment]
Maybe check the nagios log, might be caused by Livestatus. You should check which process is using this memory. I can not imagine that this is related to NagVis itselfs since NagVis is served in shortly running PHP processes normally.
