### ISSUE TITLE
Centos 6 / PHP 5.3 compatibility

### ISSUE THREAD

**Issue by tatref** [NagVis/nagvis#252]
Hi,

When installing latest version (1.9.20) on Centos 6, Nagvis is not available. Log shows:

    [Wed May 20 12:21:49 2020] [error] [client 192.168.10.147] PHP Parse error:  syntax error, unexpected '[' in /usr/local/dtb/addons/nagvis/share/server/core/sources/worldmap.php on line 176, referer: http://10.91.2.114/nagvis/frontend/nagvis-js/index.php

Culprit line:

    return [$r, $s, $t];

From http://docs.php.net/manual/en/language.types.array.php, it appears that the syntax `[...]` is only valid since PHP 5.4. Also, the minimum required version as per the doc http://docs.nagvis.org/1.9/en_US/system_requirements.html is PHP 5.0.

Could this line be replaced by:

    return array($r, $s, $t);

The change seems to work (geomap is working)
What do you think of this change?

**Comment by ekrichbaum** [comment]
That change does function on more current versions of PHP.  I'm actually not sure that a fix to support an old version of PHP would be warranted or if your syntax is more preferred.  

I would just update my OS. Centos 6 is EOL in November anyway I think, but it does look like a valid fix for old that still works in current. (I tested under 7.4.6).  You can create a PR for it and see if it flies.

**Comment by tatref** [comment]
Updating OSes is not always feasible.

I wanted to have different opinions before creating the PR (I'm not a PHP expert at all)

**Comment by LarsMichelsen** [comment]
The moment we don't need much work to be compatible, I would accept patches for better compatibility.

Would also highly recommend to update CentOS or at least PHP :-).

**Comment by tatref** [comment]
Yeah sure, update is planed for CentOS, but you know how things go :-)
About PHP, the version we use is the one provided by the OS, so no luck here.

I created a PR: https://github.com/NagVis/nagvis/pull/254
If you think it's not worth it, I'll create another PR to change the supported PHP version in the docs.
