### ISSUE TITLE
Gadgets and javascript graphs

### ISSUE THREAD

**Issue by Mikesch-mp** [NagVis/nagvis#26]
Hello,

i try to use serveral different javascripts to create some graphs for nagvis. The code itself works and graph is shown when the gadget is directly called via url nagvis/userfiles/gadgets/test.php?opts=no_perf but no from inside of a map in nagvis.
Example gadget with js code can be downoaded from http://goo.gl/AggmOe

Hope there is a solution for this problem.

Best regards,
Carsten

**Comment by LaMi-** [comment]
Please check whether or not the JS files you include can be loaded from the path you configured. You should see this in your browsers debug console or the webserver error log. Maybe you get 404 errors becaus you are using the wrong. path.
