### ISSUE TITLE
Fix: php7.4 Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by Tux12Fun** [NagVis/nagvis#265]
Bug exists in latest Version 1.9.20

File:   GlobalMapCfg.php Line: 970

     // Replace default integer object IDs (are added with "_[index]" during config parsing)
            if($id !== 0 && $id[0] == '_') {
                $todo = true;
            }

---- Change to  works for me ---- 

     // Replace default integer object IDs (are added with "_[index]" during config parsing)
            if($id !== 0 && isset($id[0]) && $id[0] == '_') {               // Added isset Statement
                $todo = true;
            }

**Comment by Tux12Fun** [comment]
Found the next bug:

File: CoreAuthModPDO.php Line: 94

           return intval($data['userId']);


---- Change to works for me ----

        $data = $res->fetch();
        if (isset($data['userId'])){
           return intval($data['userId']);
        }else{
           return intval(null);
        }

**Comment by LMS235** [comment]
have you created a pull request? Error is still in 1.9.21

**Comment by LarsMichelsen** [comment]
Just pushed fixes for the both issues. Both differ from your approaches. Would be nice if you could test the latest nightly build from http://nagvis.org/downloads to verify that both issues are fixed.

**Comment by Foxeronie** [comment]
Hey!
I tried the nightly build, after getting the error mentioned in this issue.
Now I get this error message:
```
Error: (0) in_array() expects parameter 2 to be array, bool given
URL: /nagvis/frontend/nagvis-js/index.php?mod=Map&act=view&show=Z-Racks
File: /nfs/icinga/nagvis/share/server/core/classes/GlobalMapCfg.php
Line: 1028
#0 [internal function]: nagvisExceptionErrorHandler()
#1 /nfs/icinga/nagvis/share/server/core/classes/GlobalMapCfg.php(1028): in_array()
#2 /nfs/icinga/nagvis/share/server/core/classes/GlobalMapCfg.php(488): GlobalMapCfg->checkMapConfigIsValid()
#3 /nfs/icinga/nagvis/share/frontend/nagvis-js/classes/FrontendModMap.php(94): GlobalMapCfg->readMapConfig()
#4 /nfs/icinga/nagvis/share/frontend/nagvis-js/classes/FrontendModMap.php(80): FrontendModMap->showViewDialog()
#5 /nfs/icinga/nagvis/share/server/core/functions/index.php(120): FrontendModMap->handleAction()
#6 /nfs/icinga/nagvis/share/frontend/nagvis-js/index.php(53): require('/nfs/icinga/nag...')
#7 {main}
```

Should I open another issue for this?

Thanks in advance.

Best regards,
Patrick

**Comment by LarsMichelsen** [comment]
Just pushed a fix for the new issue. I was unable to reproduce the issue, therefore I could not confirm the fix.
