### ISSUE TITLE
Unable to open Nagvis 1.9.18 with PHP 7.2.24 

### ISSUE THREAD

**Issue by CaliforniaDataSufer** [NagVis/nagvis#268]
I have recently installed Nagios, Nagvis, and OMD on my local ubuntu machine. I am able to launch Nagios and OMD web ui without issues. However, when I attempt to launch Nagvis via `http://localhost/nagvis/frontend/nagvis-js/index.php`

I receive the following error

`Error: (0) The each() function is deprecated. This message will be suppressed on further calls (/usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php:2942)

#0 [internal function]: nagvisExceptionErrorHandler(8192, 'The each() func...', '/usr/share/nagv...', 2942, Array)
#1 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(2942): each(Array)
#2 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(985): Dwoo_Compiler->mapParams(Array, Array, 0)
#3 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(668): Dwoo_Compiler->addBlock('topLevelBlock', Array, 0)
#4 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Template/String.php(369): Dwoo_Compiler->compile(Object(Dwoo), Object(Dwoo_Template_File))
#5 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo.php(363): Dwoo_Template_String->getCompiledTemplate(Object(Dwoo), Object(Dwoo_Compiler))
#6 /usr/share/nagvis/share/frontend/nagvis-js/classes/NagVisLoginView.php(85): Dwoo->get(Object(Dwoo_Template_File), Array)
#7 /usr/share/nagvis/share/frontend/nagvis-js/classes/FrontendModLogonDialog.php(48): NagVisLoginView->parse()
#8 /usr/share/nagvis/share/server/core/functions/index.php(120): FrontendModLogonDialog->handleAction()
#9 /usr/share/nagvis/share/frontend/nagvis-js/index.php(57): require('/usr/share/nagv...')
#10 {main}`

I have tried to follow the steps here to no success: https://stackoverflow.com/questions/46492621/how-to-resolve-this-deprecated-function-each-php

**Comment by LarsMichelsen** [comment]
Use some more recent NagVis version. The issue has already been fixed.
