### ISSUE TITLE
Nagvis LDAPS authetication

### ISSUE THREAD

**Issue by R00T88** [NagVis/nagvis#269]
Hi all,
i'm trying to setup ldaps auth for nagvis but not able to get it working.

/opt/rh/httpd24/root/etc/httpd/conf.d/nagvis.conf

AuthBasicProvider ldap
AuthLDAPURL "ldap://XXXX:636/dc=test,dc=it"
AuthLDAPBindDN "uid=test,OU=AdminUsers,OU=IT,DC=test,DC=it"
AuthLDAPBindPassword "sdfs"
AuthName "Auth"
AuthType Basic
require ldap-user test

into nagvis.ini.php i add this settings

logonmodule="LogonMixed"
logonenvvar="REMOTE_USER"
logonenvcreateuser="1"
logonenvcreaterole="Guests"

i'm still able to login as local admin nagvis account but not with ldap account.
LDAP accept only connections on port 636 SSL
Can someone help me out?

Thanks

**Comment by LarsMichelsen** [comment]
Sorry, can not provide configuration help here.

**Comment by jellyownsyou** [comment]
Could you please provide me with the solution. In my case it works with 3268 (ldap) port but not with 636 (ldaps). But other applications work with 636 port.
