### ISSUE TITLE
Error (Error): Call to undefined function json_encode()array(1) { [0]=> array(2) { ["function"]=> string(15) "nagvisException" ["args"]=> array(1) { [0]=> object(Error)#12 (7)

### ISSUE THREAD

**Issue by infracoop** [NagVis/nagvis#275]
![imagen_2020-11-09_102846](https://user-images.githubusercontent.com/74200975/98568112-599ed980-2276-11eb-86f1-e0dde3fe1a64.png)

when installing nagvis it throws an error string which allows me to see code and not the page frotnend

**Comment by LarsMichelsen** [comment]
Seems your PHP installation is missing the required JSON modules.
