### ISSUE TITLE
unable to add map 

### ISSUE THREAD

**Issue by dspape** [NagVis/nagvis#276]
This is the first time I have installed nagvis.
I am already using nagios core and it is working, now I have installed icinga then nagvis.
first login, I try to create a map that I want used for nagios.
as soon as I create a nagvis map gives me an http error.

![http_error](https://user-images.githubusercontent.com/68599892/99874906-b3df5900-2beb-11eb-9f7d-df270d4b831c.png)

**Comment by LarsMichelsen** [comment]
Looks like a very old NagVis version. Can not support it.
However, error 500 is normally showing more details in the web server error log.
