### ISSUE TITLE
Cannot choose perfdata in weathermap lines 

### ISSUE THREAD

**Issue by fledorze** [NagVis/nagvis#277]
I just installed the latest version on DebianI want to  Stretch/Apache 2.4.25-3/PHP 7.0.33

My perfdata output is  : 
 'traffic_in'=6301187.31b/s;0:16000000;0:18000000;0;20000000 'traffic_out'=1323595.40b/s;0:16000000;0:18000000;0;20000000 'packets_discard_in'=0.00%;0:10.00;0:20.00;0;100 'packets_error_in'=0.00%;0:10.00;0:20.00;0;100 'packets_discard_out'=0.00%;0:10.00;0:20.00;0;100 'packets_error_out'=0.00%;0:10.00;0:20.00;0;100 'packets_crc_in'=0.00%;;;0;100 'traffic_in_percent'=31.51%;0.00:80.00;0.00:90.00;0;100 'traffic_out_percent'=6.62%;0.00:80.00;0.00:90.00;0;100

According to https://www.nagvis.org/downloads/changelog/1.9.18, I should be able  to choose which perfdata is used for weathermap lines by using line_label_in/line_label_out options. I configured them with 'traffic_in_percent'/'traffic_out_percent'

But NagVis still says : WeatherMap Line error : Value 0 is not percentage value , WeatherMap Line error : Value 1 is not percentage value 

As if the line_label_in/line_label_out options were taken in account.

Could you help ?

**Comment by LarsMichelsen** [comment]
Sorry, I can not provide support here.
