### ISSUE TITLE
Unable to open auth database (sqlite auth.db): "Initial DB query (PRAGMA journal_mode = wal) failed" BUG

### ISSUE THREAD

**Issue by esoulenq** [NagVis/nagvis#278]
Hello
When I open NAGVIS on my webserver : 
I have this issue :
Unable to open auth database (sqlite: nagvis/etc/auth.db): "Initial DB query (PRAGMA journal_mode = wal) failed"

**Comment by LarsMichelsen** [comment]
may be a corrupted sqlite auth.db file. You could try to move the auth.db file away. NagVis will create an empty one. But you will miss you users and permissions after doing this.
