### ISSUE TITLE
Javascript error occured

### ISSUE THREAD

**Issue by speynaud** [NagVis/nagvis#279]
I have Javascript error on my nagvis v1.9.23, I used nagvis on EyesOfNetwork 5.3 working on Azure, YUM is uptodate.

My error :
Javascript error occured: TypeError: g_view is null https://xxx.xxx.xxx.xxx/nagvis/frontend/nagvis-js/js/frontend.js?v=1.9.23 (769)
Javascript error occured: Uncaught TypeError: Cannot read property 'update' of null https://xxx.xxx.xxx.xxx/nagvis/frontend/nagvis-js/js/frontend.js?v=1.9.23 (769)

Displayed in pink textbox on the top of map and disapear after refresh

It seems I have Javascript error it's sure, but I don't know what is the root cause of it, can you help me please?

Thank you

**Comment by LarsMichelsen** [comment]
You may post your map config to reproduce it or start over with an empty map and try to build some minimal config that triggers the issue.

**Comment by speynaud** [comment]
Thank you for answer, I will try it.
For your information in fact I used Nagvis in EyesOfNetwork, where I open nagvis map in thruk panorama with a "Generic Url Panel"
In my panorama I load 3 nagvis map.
I know in panorama we can open directly "Nagvis Map" but when I use it, no maps found when I field Nagvis Base Url : /nagvis
Do you know it? Can you help me?
Thank you so much

**Comment by LarsMichelsen** [comment]
Have never used EyesOfNetwork nor Panorama, sorry. Will close this ticket for now.
