### ISSUE TITLE
Nagvis Hover Maps Service Status

### ISSUE THREAD

**Issue by hitchmoughl** [NagVis/nagvis#28]
Hi,
Was wondering if someone could provide some advice. I am currently running Nagios 4.0.8 / Nagvis 1.9a1 with mk_livestatus as the backend. Everything is running fine apart from one small issue. I have services defined for some Windows machines and if any of the services encounter problems the host status turns critical, but the service status does not change in the hover map until I F5 the webpage. Its a minor annoyance, but can anyone please advise on how to get the service status to auto update in the hover maps? its annoying as for some systems I have several services defined.
Thanks in advance!

**Comment by LaMi-** [comment]
The service states are not updated in the hover menu of host objects. Did I get that right? Or do you have service objects and their hover state is not being updated?

**Comment by hitchmoughl** [comment]
Hi, thanks for the response 😊
The service objects hover state is not being updated. So when i have a service alert the host icon will flash red and in the hover the hosts state will display critical but the service state will not update unless I refresh the page?

**Comment by hitchmoughl** [comment]
Sorry that response was poor.For example I have services checking that db listening ports are up on several servers (amongst other checks that exhibit the same behaviour).  If the check fails the host status will show as critical but the service states in the hover do not update until I refresh the screen and this happens for all services.

**Comment by hitchmoughl** [comment]
Sorry for my initial poor response. Does the above answer your question? Your support is appreciated.

**Comment by LaMi-** [comment]
please show me some screenshots explaining the issues. I would also like to see the hover menus of the affected objects.

**Comment by hitchmoughl** [comment]
Thanks for the response LaMi. I'll capture this and post it ASAP.

**Comment by hitchmoughl** [comment]
Hi LaMi,
Information attached as requested. Many thanks for your support..
[php.txt](https://github.com/NagVis/nagvis/files/62428/php.txt)

[screenshots.pdf](https://github.com/NagVis/nagvis/files/62432/screenshots.pdf)

**Comment by LaMi-** [comment]
Sorry, mixed it with another bug. This is not fixed yet.

**Comment by LarsMichelsen** [comment]
Sorry for the late response. I found the time now to analyze and fix this issue.

Thanks for providing the details.
