### ISSUE TITLE
Zoom option "fill screen" is not recognized

### ISSUE THREAD

**Issue by Samuel-Priour** [NagVis/nagvis#281]
when i set zoom option fill screen on my map, i get a blank page with this error in the menu modify view/appearence/zoom = NaN
this is what i get i get in my url bar : "nagvis-js/index.php?mod=Map&act=view&show=123456&zoom=NaN#"
the zoom bar is at the max, when i scroll down the zoom bar i can see the map
it seems the zoom factor is more than 200% with fill screen option

everything is fine with zoom set to 75%, 100%, 125% ....

nagvis 1.9.25

**Comment by LarsMichelsen** [comment]
Sorry, can not help you with this issue.
