### ISSUE TITLE
display website as iframe in rotation pool

### ISSUE THREAD

**Issue by jonwitts** [NagVis/nagvis#282]
Hi,

We are running NagVis 1.9.20 and I have come across an issue trying to add an external website into a rotation pool using the iframe method as documented in the help guide. 

I have the following as the URL entry in my rotation definition: [iframe:http://www.bbc.co.uk] yet when loading that page I get the following error in Chrome console: **Failed to launch 'iframe:http://www.bbc.co.uk' because the scheme does not have a registered handler.** and this in Firefox console: **Prevented navigation to “iframe:http://www.bbc.co.uk” due to an unknown protocol.** 

Any pointers on how to debug or get iframe websites to display would be hugely appreciated... 

Jon

**Comment by LarsMichelsen** [comment]
Have no Idea, sorry. The setting looks OK. Can not provide in depth support.
