### ISSUE TITLE
Difference in data displayed nagios service line and collection. 

### ISSUE THREAD

**Issue by vdalcin** [NagVis/nagvis#283]
<img width="520" alt="Captura de Tela 2021-04-04 às 16 45 14" src="https://user-images.githubusercontent.com/10339135/113642199-a637e680-9655-11eb-9256-650139186732.png">

I'm using Checkmk 2.0.0p1 and nagvis 1.9.25

**Comment by LarsMichelsen** [comment]
Could be related to 1000 / 1024 conversions. Not sure about this. But can sadly not support you with this issue here. The next NagVis version will fix some issue related Bits in weathermap lines. But I'm not sure whether or not this will solve your issue.
