### ISSUE TITLE
How change background color of main page ?

### ISSUE THREAD

**Issue by emi65** [NagVis/nagvis#286]
Hi
I update nagvis from 1.9.13 to 1.9.25

In .13 version I was able to make the main product page in black color
After upgrade to .25 version the main page is white
How can I change the background color of main page ?

thanks 
Emilio

**Comment by LarsMichelsen** [comment]
I'm not aware of related changes. But it's also hard to guess what you did and what is not working anymore. Closing this now since it's very old.
