### ISSUE TITLE
Possible security problem when using external URL in rotation pool

### ISSUE THREAD

**Issue by swedieman** [NagVis/nagvis#29]
Since the URL is sent as a GET variable (e.g. https://localhost/nagvis/frontend/nagvis-js/index.php?mod=Url&act=view&show=http://www.google.com) anyone, with the permission to view an external URL, may change the "show" query parameter to anything, even a local file on the server, using file://... since file_get_contents() is used.

The "quick" fix would probably be to send "show" with POST instead of get so only the URL set in the config is used.

A better fix would probably be to never pass any data from URL (or file) through the local server, and instead put the external URL in an iframe. In that way only the browser connects to the external URL.

**Comment by LaMi-** [comment]
Hm, did you really try to get local files this way?

**Comment by barry-luijten** [comment]
Yes, I did and it works:
https://localhost/nagvis/frontend/nagvis-js/index.php?mod=Url&act=view&show=file:///etc/passwd
This actually turned up as a finding in a PEN test that was performed against our NagVis instance (1.7).

**Comment by LarsMichelsen** [comment]
Just fixed the second issue.  Please check out future nightly builds or releases and let me know whether or not the issue is solved.
