### ISSUE TITLE
You are not allowed to see this page

### ISSUE THREAD

**Issue by elnicouru** [NagVis/nagvis#290]
NagVis version   1.9
    Distribution     CentOS Linux release 7.9.2009 (Core)
    Apache version   2.4.6
    PHP version      PHP 5.4.16
    Centreon Version 21.04.0
    Are there error messages in webservers error log?  no
    Browser used (Equal behaviour in other browsers?) Yes
    Are there JavaScript errors in the browser? NO
 

Hi to all

I`ve installed the NAGVIS version mentioned but when i add a host or a service on the NAGVIS map and i click on the object to view the details in CENTREON, the sofware shows me the message "You are not allowed to see this page". Ive checked on 3 browsers but the error still stays on.

What i can do ?? or what i must check/re check ?

**Comment by LarsMichelsen** [comment]
Sorry, not using Centreon. Can not provide support for it here.
