### ISSUE TITLE
[Database] Add option to use SSL / TLS option to connect to MariaDB databases

### ISSUE THREAD

**Issue by delmelo** [NagVis/nagvis#295]
I use Centreon (version 20.10.4) and Nagvis to displays monitor objects in maps.

I would like to enable SSL option for connecting to my MariaDB server and avoid using _login:password._

In _nagvis.ini.php_ file, I define a "centreon_backend" and I can only set _dbname_ and _dbpass_ parameters:

`[backend_centreonbroker]`
`backendtype="centreonbroker"`
`statushost=""`
`dbhost="{{ host_name }}"`
`dbport=3306`
`dbname="{{ mysql_centstorage_db }}"`
`dbuser="{{ Centreon_mariadb_username }}"`
`dbpass="{{ Centreon_mariadb_password }}"`
`dbinstancename="default"`
`htmlcgi="/centreon"`

This new feature can secure connections from MariaDB and Nagvis using certificates and avoiding clear text information including exchanged passwords between the server and client.

**Versions :** 
Centreon : 20.10.4
MariaDB server :  10.3.17
Nagvis : 1.9.25

**Comment by LarsMichelsen** [comment]
It's a feature of the backend you use, it's not part of NagVis. You will have to contact the author of your backend to get support with this.
