### ISSUE TITLE
NagVis map editor - gadets - gadget_url and input field

### ISSUE THREAD

**Issue by solarmon** [NagVis/nagvis#297]
Hi,

Nagios XI Version: 5.8.5
NagVis Version: 1.9.8
PHP Version: 5.4.16

I have come across an issue when editing gadgets. I needed to add "conf=true" to the gadget_url pointing to the gadget .php file.

However, the map editor for the gadget object only provides a drop-down list of gadget scripts to select and does not allow you to customise the  gadget_url text to add "conf=true" to it.

I had to export the map, add it manually, and then import it. But now, this breaks the gadget_url field and it displays:

"Current value is not a known option - falling back to input field"

Now gadget_url is an input field and it can be edited appropriately.

So I suppose the issue/question is how to change gadget_url in to an input field in the first place, without have to go through the exprt/import trick?

Thank you.

**Comment by LarsMichelsen** [comment]
Use the option gadget_opts. Have a look at the documentation for further information.
