### ISSUE TITLE
Error - cellsperrow is deprecated but not documented

### ISSUE THREAD

**Issue by gvmorley** [NagVis/nagvis#30]
It appears that the configuration item 'cellsperrow' under [index] is deprecated, but there is no mention of this in the documentation (online) or in the sample nagvis.ini.php

Because of this, NagVis throws up a large red error message. This is easily resolved by commenting out the config item.

Very minor, but could cause confusion. I'm running:

NagVis Version: 1.8.5
PHP Version 5.3.3

This is part of the OP5 Monitor product (version 7.1.6).

**Comment by LaMi-** [comment]
Thanks for the info. I just marked the var as deprecated in the docs.
