### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by mirkus1234** [NagVis/nagvis#302]
hi all, 

i have installed nagvis + nagios following official guide.

my problem is that when trying to access http://IP/nagios/nagvis i obtain a 403 (forbidden).

anyone has met this problem or can give me support?

tnx in advance mirko

**Comment by tafi786** [comment]
Hi mirkus the url should be http://ip/nagvis please remove the "nagios" to access the nagvis and visa vera if you want to access nagios

**Comment by LarsMichelsen** [comment]
Closing inactive issue
