### ISSUE TITLE
Error access nagvis Redhat

### ISSUE THREAD

**Issue by gildasiosousa** [NagVis/nagvis#309]
I did installation by ./install.sh but I can't access nagvis to Redhat 8.
But present 403 error
Forbidden
You don't have permission to access this resource.
Error log httpd:
 [Wed Jan 19 14:07:10.085106 2022] [authz_core:error] [pid 1176149:tid 140031888971520] [client 192.168.22.45:62262] AH01630: client denied by server configuration: /nagvis/nagvis/share/frontend/nagvis-js/index.php

**Comment by gildasiosousa** [comment]
Configuration executed with PHP 7.4

**Comment by T100D** [comment]
Is SELINUX enabled?

**Comment by gildasiosousa** [comment]
Thanks! by help T100D, but SELINUX is disabled.

**Comment by gildasiosousa** [comment]
My httpd conf looks like this:

Alias /nagvis/ "/nagvis/nagvis/share/"
<Directory "/nagvis/nagvis/share/">
  Options FollowSymLinks
  AllowOverride none
  #Order allow,deny
  #Allow from all
  Require all granted

  <IfModule mod_authz_core.c>
    # Apache >= 2.4
    Require all granted
  </IfModule>
  <IfModule !mod_authz_core.c>
    # Apache < 2.4
    Order allow,deny
    Allow from all
  </IfModule>

  # To enable Nagios basic auth on NagVis use the following options
  # Just uncomment it. Maybe you need to adjust the path to the
  # Auth user file.
  #
  # If you use the NagVis internal auth mechanism based on the web
  # for you won't need this.
  #
  #AuthName "NagVis Access"
  #AuthType Basic
  #AuthUserFile /nagios/etc/htpasswd.users
  #Require valid-user

  # With installed and enabled mod_rewrite there are several redirections
  # available to fix deprecated and/or wrong urls. None of those rules is
  # mandatory to get NagVis working.
  <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /nagvis/nagvis

    # Use mod_rewrite for old url redirection even if there are php files which
    # redirect the queries itselfs. In some cases the mod_rewrite redirect
    # is better than the php redirect.
    #
    # Using the php redirect seems to be better in some cases where https/http servers
    # are mixed. For example in OMD setups where using apache own mode and https in the
    # frontend and http in the backend apache servers.
    #
    # Disabling this redirect by default in the hope that the php direct works better.
    #RewriteCond %{REQUEST_URI} ^/nagvis/nagvis(/config\.php|/index\.php|/|)(\?.*|)$
    #RewriteRule ^(.*)$ /nagvis/nagvis/frontend/nagvis-js/%1%2 [R=301,L]

    # Redirect old regular map links
    RewriteCond %{REQUEST_URI} ^/nagvis/nagvis/frontend/(wui|nagvis-js)
    RewriteCond %{QUERY_STRING} map=(.*)
    RewriteRule ^(.*)$ /nagvis/nagvis/frontend/nagvis-js/index.php?mod=Map&act=view&show=%1 [R=301,L]

    # Without map= param
    RewriteCond %{REQUEST_URI} ^/nagvis/nagvis/frontend(/wui)?/?(index.php)?$
    RewriteRule ^(.*)$ /nagvis/nagvis/frontend/nagvis-js/index.php [R=301,L]

    # Redirect old rotation calls
    RewriteCond %{REQUEST_URI} ^/nagvis/nagvis/frontend/nagvis-js
    RewriteCond %{QUERY_STRING} !mod
    RewriteCond %{QUERY_STRING} rotation=(.*)
    RewriteRule ^(.*)$ /nagvis/nagvis/frontend/nagvis-js/index.php?mod=Rotation&act=view&show=%1 [R=301,L]
  </IfModule>
</Directory>
~

**Comment by gildasiosousa** [comment]
I managed to solve.
install multiple versions of PHP php56, junto com o php72

```
dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
dnf makecache
dnf install -y php56 php56-php-fpm
dnf install php56*
dnf install php56* --skip-broken --nobest
cat > /var/www/cgi-bin/php56.fcgi << EOF
#!/bin/bash
exec /bin/php56-cgi
EOF
chmod 755 /var/www/cgi-bin/php*
```
