### ISSUE TITLE
NagVis: Uncaught ReferenceError: yOffset is not defined 

### ISSUE THREAD

**Issue by TheFlyingCorpse** [NagVis/nagvis#31]
NagVis 1.9b2:
Error message displayed on maps using line_type=14:
----
Loading...
x
Error: Javascript Error
Javascript error occured: Uncaught ReferenceError: yOffset is not defined http://nagvis.domain.local/nagvis/frontend/nagvis-js/js/NagVisCompressed.js (3313)
----

Commenting out all references of "line_type" out of the .cfg being rendered (set to 14 and worked prior to upgrade from 1.8.x) is one workaround, another is changing type to 13, a third workariond is replacing yOffset with 1 in the offending .js file and it renders the arrows with textboxes correctly.

From:
'#ffffff', '#000000', (x-labelWidth), parseInt(y + yOffset),

To:
'#ffffff', '#000000', (x-labelWidth), parseInt(y + 1),
(Ugly "workaround", it will render one side of every line correctly, the other side will have both values as the same percent)

Perfdata:
'in'=335.0;;;0;10000000000 'inerr'=0;;;0;100 'indrop'=0;;;0;100 'out'=0.0;;;0;10000000000 'outerr'=0;;;0;100 'outdrop'=0;;;0;100 'Input packets'=0.5packets/s 'Output packets'=0packets/s 'Input error'=0% 'Output error'=0% 'Input drop'=0% 'Output drop'=0%

**Comment by TheFlyingCorpse** [comment]
The issue persists (copied the lines modified over to 1.9b3). Tried other computers with and without clean caches, the issue persists.

**Comment by LaMi-** [comment]
Which lines did you copy to which file? I you copied it to ElemenLine.js, you need to remove the NagVisCompressed.js to make ElementLine.js being loaded. Otherwise your changes will not be loaded as NagVis is prefering the compressed file over the uncompressed ones.

**Comment by TheFlyingCorpse** [comment]
Deleted the NagVisCompressed.js, the error is now:
"Javascript error occured: 'yOffset' is undefined http://nagvis.domain.local/nagvis/frontend/nagvis-js/js/ElementLine.js (470)"

Lines 466 through 474 of ElementLine.js:
----------
        // Paint the second label in case of line type 14
        if (this.obj.conf.line_type == '14') {
            txt = this.perfdata[2+id][1] + this.perfdata[2+id][2];
            labelWidth = this.getLabelWidth(txt);
            this.obj.trigger_obj.appendChild(
                renderNagVisTextbox(this.obj.conf.object_id+'-link'+(id+1),
                                    '#ffffff', '#000000', (x-labelWidth), parseInt(y + yOffset),
                                    this.obj.conf.z, 'auto', 'auto', '<b>' + txt + '</b>'));
        }
----------

**Comment by LaMi-** [comment]
You also need to apply https://github.com/NagVis/nagvis/commit/93120f105852f7cca677c9edc002afc8983f8300

**Comment by TheFlyingCorpse** [comment]
Excellent, consider this resolved (as you already did) :+1:
