### ISSUE TITLE
[Problem] Installing Nagvis on another server

### ISSUE THREAD

**Issue by AmoryHoub** [NagVis/nagvis#311]
Hello to all,
I have a small problem, I would like to set up Nagvis connected to Centreon but on another server, I followed the procedure of the site "sugarbug" for the installation by taking into account the files of Centreon by making a samba share in order to recover them on my Nagvis server but without result. If someone succeeded could help me by sending me his configuration or the tuto he would have followed.

Thanks in advance and have a nice day

**Comment by LarsMichelsen** [comment]
Sorry I can not help with Centreon since I am not using it.
