### ISSUE TITLE
[Problème] Installation de Nagvis sur un autre serveur

### ISSUE THREAD

**Issue by AmoryHoub** [NagVis/nagvis#312]
Bonjour à tous,
J'ai un petit problème, je souhaiterais mettre en place Nagvis connecter à Centreon mais sur un autre serveur, j'ai suivi la procédure du site "sugarbug" pour l'installation en prenant en compte les fichiers de centreon en faisant un partage samba afin de les récupérer sur mon serveur Nagvis mais sans résultat. Si quelqu'un a réussi pourrait m'aider en m'envoyant sa configuration ou le tuto qu'il aurait suivi.

Merci d'avance et bonne journée

**Comment by LarsMichelsen** [comment]
Sorry I can not help with Centreon since I am not using it.
