### ISSUE TITLE
NagVis: Saving modified and unmodified maps gives error: The attribute is unknown.

### ISSUE THREAD

**Issue by TheFlyingCorpse** [NagVis/nagvis#32]
On creating new or modified maps in NagVis 1.9b2 it gives the following error in Chrome 47:
"The attribute is unknown."

It is not possible to add and modify objects within the map either, the same error is reported back.

**Comment by LaMi-** [comment]
Can not reproduce this issue. Might this be some kind of caching issue? Please clean your browser to verify that it is not.

**Comment by TheFlyingCorpse** [comment]
I have reproduced the issue in both IE11 and Chrome now, both with cleared caches. How can I get you more information to reproduce this? 

I've managed to add new maps but not new objects to them.

**Comment by LaMi-** [comment]
Please try to send me a step by step guide on how to reproduce this issue.

**Comment by TheFlyingCorpse** [comment]
1. Open any map in NagVis
2. Edit Map -> Add Host (or service)
3. Browse for and find a host you would like to add
4. Click save, the error "The attribute is unknown."
No error in apache's error_log for this.

At the moment it is using the head of this git repo.

backend is icinga 1.13.3 via ndomy name, it has an alternative backend which is icinga 2.4.1, which has the exact same error messages.

**Comment by TheFlyingCorpse** [comment]
I modified the output to throw me the key it fails at, it fails at "nagvis_session". Investigating futher.
Sidenode, this installation has been upgraded from at least 1.6, via 1.7 a year ago to 1.8 this summer and about a week back to 1.9b3 :)

**Comment by TheFlyingCorpse** [comment]
Tried fresh install of Nagvis on the host with nothing in it from before, the issue is still present.
SLES 11 SP3:
PHP 5.2.14 with Suhosin-Patch 0.9.7 (cli) (built: Sep  5 2012 10:07:29)
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.2.0, Copyright (c) 1998-2010 Zend Technologies

I do not see this issue on Debian Jessie:
PHP 5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

I went ahead and upgraded from SLES 11 SP3 to SLES 11 SP4, it is still not working "out of the box" (default installation, no modifications on my end).
PHP 5.3.17 (cli)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

**Comment by TheFlyingCorpse** [comment]
Upgrading to PHP 5.3 resolved the issue, feel free to close this issue.

**Comment by LaMi-** [comment]
Very interesting. Thanks for analyzing. I'll test the 1.9 code  with older PHP versions.

**Comment by LaMi-** [comment]
Fixed with commit e5f81596e79316cdb6e0149d4847afdc4f98db05
