### ISSUE TITLE
Deleted hosts and services from Icinga2 are still displayed in automap

### ISSUE THREAD

**Issue by TimRutte** [NagVis/nagvis#34]
Hi,

deleted hosts and services from Icinga2 are still displayed in automap. If I delete a host or a service in a Icinga2 conf, the host or service is no longer visible in Icingaweb2 but still visible in nagvis after service restart. I also tried to regenerate the automap but they are still visible. It seems that nagvis ignores the active flag for hosts and services from icinga2. 

Icinga2 version: r2.4.1-1
Incinga Web 2 version: 2.1.2-2~ppa1
Nagvis version: 1:1.7.10+dfsg1-2

System information:
  Platform: _NAME="Ubuntu 14.04.3 LTS
  Platform version: ID="14.04
  Kernel: Linux
  Kernel version: 3.19.0-43-generic
  Architecture: x86_64

Tim

**Comment by LaMi-** [comment]
Patches / pull requests are welcome. The bug is located somewhere in share/server/core/classes/GlobalBackendndomy.php. This backend is used to connect to the icinga DB.

But I really recommend to use the livestatus backend instead.

**Comment by dnsmichi** [comment]
This commit partially fixes the problem already, though there are more queries affected (basically every query which involves a join on the objects table).

    commit be9b9fce9e740c22fac9b25fca04a814afd7d7b7
    Author: Lars Michelsen <lm@larsmichelsen.com>
    Date:   Wed Aug 19 18:03:11 2015 +0200
    
        FIX: NDO/IDO backend: Correctly excluding deprecated objects from hosts
        and host groups
    
        Thanks to mwaldmueller for providing the patch!

The PR is located over here: https://github.com/NagVis/nagvis/pull/56

**Comment by LarsMichelsen** [comment]
Just merged the PR. Should be fixed.
