### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by PMD3520** [NagVis/nagvis#349]
after installing nagvis i get this error when i go to the page, if anyone can help me

function iso8859_1_to_utf8($string) { return mb_convert_encoding($string, 'UTF-8', 'ISO-8859-1'); } Error (Error): Call to undefined function iso8859_1_to_utf8()array(1) { [0]=> array(2) { ["function"]=> string(15) "nagvisException" ["args"]=> array(1) { [0]=> object(Error)#28 (7) { ["message":protected]=> string(46) "Call to undefined function iso8859_1_to_utf8()" ["string":"Error":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(60) "/usr/share/nagvis/share/server/core/classes/GlobalMapCfg.php" ["line":protected]=> int(338) ["trace":"Error":private]=> array(8) { [0]=> array(5) { ["file"]=> string(60) "/usr/share/nagvis/share/server/core/classes/GlobalMapCfg.php" ["line"]=> int(454) ["function"]=> string(15) "parseConfigFile" ["class"]=> string(12) "GlobalMapCfg" ["type"]=> string(2) "->" } [1]=> array(5) { ["file"]=> string(58) "/usr/share/nagvis/share/server/core/classes/GlobalCore.php" ["line"]=> int(450) ["function"]=> string(13) "readMapConfig" ["class"]=> string(12) "GlobalMapCfg" ["type"]=> string(2) "->" } [2]=> array(5) { ["file"]=> string(71) "/usr/share/nagvis/share/frontend/nagvis-js/classes/NagVisHeaderMenu.php" ["line"]=> int(324) ["function"]=> string(11) "getListMaps" ["class"]=> string(10) "GlobalCore" ["type"]=> string(2) "->" } [3]=> array(5) { ["file"]=> string(71) "/usr/share/nagvis/share/frontend/nagvis-js/classes/NagVisHeaderMenu.php" ["line"]=> int(82) ["function"]=> string(9) "getMacros" ["class"]=> string(16) "NagVisHeaderMenu" ["type"]=> string(2) "->" } [4]=> array(5) { ["file"]=> string(74) "/usr/share/nagvis/share/frontend/nagvis-js/classes/FrontendModOverview.php" ["line"]=> int(77) ["function"]=> string(10) "__toString" ["class"]=> string(16) "NagVisHeaderMenu" ["type"]=> string(2) "->" } [5]=> array(5) { ["file"]=> string(74) "/usr/share/nagvis/share/frontend/nagvis-js/classes/FrontendModOverview.php" ["line"]=> int(55) ["function"]=> string(14) "showViewDialog" ["class"]=> string(19) "FrontendModOverview" ["type"]=> string(2) "->" } [6]=> array(5) { ["file"]=> string(55) "/usr/share/nagvis/share/server/core/functions/index.php" ["line"]=> int(120) ["function"]=> string(12) "handleAction" ["class"]=> string(19) "FrontendModOverview" ["type"]=> string(2) "->" } [7]=> array(4) { ["file"]=> string(52) "/usr/share/nagvis/share/frontend/nagvis-js/index.php" ["line"]=> int(53) ["args"]=> array(1) { [0]=> string(55) "/usr/share/nagvis/share/server/core/functions/index.php" } ["function"]=> string(7) "require" } } ["previous":"Error":private]=> NULL } } } }

**Comment by LarsMichelsen** [comment]
What version did you install? Is this a daily build or something you picked from master?

**Comment by LarsMichelsen** [comment]
Unable to reproduce, sorry. Please try again with the upcoming release and report back in case of an issue.
