### ISSUE TITLE
Javascript error 

### ISSUE THREAD

**Issue by pgundersen** [NagVis/nagvis#35]
Hi,

We are running Nagvis Beta git Master.
After I have logged on, I get a Javascript error on the main page as the picture view

![capture](https://cloud.githubusercontent.com/assets/16575117/12320426/fc2c1fb8-baa8-11e5-8816-2b157ddf3786.PNG)

Need some help to locate the problem.

**Comment by LaMi-** [comment]
Could you please check the apache error log for related messages?

Maybe you can also take a look at the access log and look for lines refering ajax_handler.php together with a HTTP status code != 200. Please post them if you can find any.

**Comment by pgundersen** [comment]
i got this error message 
```
[Wed Feb 03 09:31:37.127836 2016] [:error] [pid 8591] [client 10.0.0.57:63837] PHP Fatal error:  Call to undefined method GlobalBackendndomy::getServiceListCounts() in /usr/share/nagvis/share/server/core/classes/CoreBackendMgmt.php on line 241, referer: https://server.localdomain/nagvis/frontend/nagvis-js/index.php
```

**Comment by LarsMichelsen** [comment]
So, is it correct that you are using the NDO MySQL backend to connect with your core? Why don't you use Livestatus?

Do you have configured one or several dynamic group objects on one or several of your maps?

**Comment by LarsMichelsen** [comment]
I just had a look at the code and it seems you had a dynamic group object containing service objects on the map while the object was using a NDO MySQL backend as data source which does not support this kind of object.

The current NagVis code missed a proper error handling for this case. I just added it to the code. It will now display an error message if you try to use the dynamic groups with invalid backends.
