### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by jlabradorg** [NagVis/nagvis#350]
Hello, I've been updating NagVis to version 1.9.35, and I've encountered this issue with some maps.

![error_issue](https://github.com/NagVis/nagvis/assets/45948474/8e54cea0-236e-4c8e-8c02-33989ca142e1)

I've also experienced the following authentication error.

![issue_2](https://github.com/NagVis/nagvis/assets/45948474/4d59defe-1bc0-49e4-846c-efa5c69fef4e)

Has anyone else experienced something similar? Thank you very much.

**Comment by T100D** [comment]
What happens when you use the nagvis admin/root account? Could be an account with no viewing privileges on the map.
