### ISSUE TITLE
Add feature: Center Map

### ISSUE THREAD

**Issue by Azef1** [NagVis/nagvis#39]
Hi,
I would like to center a backgroud-image and i doesn't see where is this feature.
So, i think this feature should be add.

Nagvis 1.9b4
thx

**Comment by LarsMichelsen** [comment]
This is currently not possible.

**Comment by lwindolf** [comment]
Such a feature would be very appreciated.

**Comment by LarsMichelsen** [comment]
I don't really understand what the benefit of implementing "a centered background image" would be.

If the background image is centered and you place an object on it, while all the map objects are still positioned top/left aligned as it is currently in NagVis, the objects will be positioned on different places of the map depending on the viewport size.

So only centering the image won't work.

**Comment by lwindolf** [comment]
Yes, centering only the image doesn't make sense. Centering the map (as the title suggest) is more like it. For me the use case is displaying multiple Nagviz maps (using browser tab cycling) on a wall display. And it does look really odd to have them left centered :-)

**Comment by LarsMichelsen** [comment]
Possible workaround: If you have a screen of fixed size, maybe you can simply increase the size of the image to fit the size of your screen with just a white background color and your image centered on it.

**Comment by Azef1** [comment]
i closed issue because it is currently not possible.
