### ISSUE TITLE
Nagvis 1.8 - cannot manage user / roles

### ISSUE THREAD

**Issue by vianneypoirot** [NagVis/nagvis#4]
Good morning,

I have a problem with account and roles management / creation.
Indeed, I have the same error message when I try to add or modify an account / role 
![2015-03-09_09h39_16](https://cloud.githubusercontent.com/assets/11386458/6551937/5b03855c-c640-11e4-8935-4fb3bdad0c55.png)

I can't find any error messages in logs (apache logs)

Here is my configuration : 
Nagvis 1.8, with ndo and sqlite3 for authentication

=========
[global]
authorisationmodule="CoreAuthorisationModSQLite"
file_group="apache"
sesscookiepath="/nagvis2"

[paths]
base="/usr/local/nagvis2/"
htmlbase="/nagvis2"

[defaults]
backend="ndomy_1"
hosturl="/centreon/main.php?p=20201&o=svc&host_search=[host_name]"
hostgroupurl="/centreon/main.php?search=[hostgroup_name]&p=20104&limit=100&list=&o=hg"
serviceurl="/centreon/main.php?p=202&o=svcd&host_name=[host_name]&service_description=[service_description]"
servicegroupurl="/centreon/main.php?p=20212&o=svcOVSG"

[index]
showrotations=1
showmapthumbs=1

[automap]

[wui]

[worker]

[backend_ndomy_1]
backendtype="ndomy"
dbhost="localhost"
dbport=3306
dbname="centstatus"
dbuser="centreon"
dbpass="centreon"
dbprefix="nagios_"
dbinstancename="poller_1"

===========

Thanks in advance

Best regards

**Comment by vianneypoirot** [comment]
Problem still here after 1.8.1 patch

**Comment by vianneypoirot** [comment]
New error with this patch, at loggin, when I arrive in overview, after few seconds, I have got this message (I have to close 3 times the window and after it's good) : 
![2015-03-10_09h00_56](https://cloud.githubusercontent.com/assets/11386458/6571086/7eadab58-c704-11e4-9066-966de63ccfe4.png)

**Comment by LaMi-** [comment]
on the form issue: please ensure your browser cache has been cleared after the update.

I can not reproduce both of the problems with the current code.

Which browser are you using?

**Comment by vianneypoirot** [comment]
After cleaning cache, I still have the problem on Javascript, but it works pour user & role management !

I'm using the last version of chrome (41.0.2272.89 m (64-bit)).

**Comment by vianneypoirot** [comment]
I precise it hapens only at login

**Comment by LaMi-** [comment]
This problem seems to occur in the hover template processing code. Do you have custom hover templates configured anywhere (hover_template in maps or hovertemplate in defaults section of main config)?

Maybe some of them are not existant (anymore)?

**Comment by vianneypoirot** [comment]
I solve problem, I discover that a map (in etc/maps directory) was with root:root owners.

I changed it and problem doesn't appear anymore

I notice 2 enhancements : 
- In overview, maps are not alphabetize (it charged 1 by 1)
- When I try to charge by maps (in my case 1.2 Mo), You have an error in web interface (Map too big)
Where could I put this 2 enhancements ?

Thanks a lot for your job and your reactivity

**Comment by LaMi-** [comment]
Hm, I don't have an explanation for the js error to be connected with the root:root permissions. But it's fine that your problem is gone.

What do you mean with alphabetize? Do you mean wrong sorting of the list or wrong styling?
What do you mean with 1.2 Mo?
