### ISSUE TITLE
Using worldmap without geomap.nagvis.org | Own worldmaps

### ISSUE THREAD

**Issue by 1tft** [NagVis/nagvis#40]
Hello,
exists there any way to use the Nagvis worldmap feature without http://geomap.nagvis.org/ ?
1. Can Nagvis work directly with OSM maps (without the API on geomap.nagvis.org)?
2. Can I download the API used on geomap.nagvis.org and install it on my own server, so that I can redirect to my own OSM server?

Background: I want to create my own OSM maps, which are not availbale via OpenStreetMap.

**Comment by LarsMichelsen** [comment]
Hi,

you are mixing two features. The geomap is using geomap.nagvis.org. The worldmap which is based on LeafletJS and OSM is not connecting with geomap.nagvis.org.

As LeafletJS supports other sources it should be possible to make NagVis use other map sources, but this is something which is currently not implemented in NagVis.

**Comment by PepeOnAChair** [comment]
Hello,
I`d like also to use mi own tile map server. I`m prepared to instal my own clone of OSMap as described here:
https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/

I just need to know if it is somehow possible to use in Nagvis - so Nagvis will use only map tiles on my own server.

Thank you
Pep.

**Comment by LarsMichelsen** [comment]
This is not possible without code changes at the moment. The URL to the tile server is hard coded in share/frontend/nagvis-js/js/ViewWorldmap.js at the moment.

Don't plan to add this feature in the near future.
