### ISSUE TITLE
Even with a Role with Auth 	logout Permitted the logout menu don't show

### ISSUE THREAD

**Issue by paulrm** [NagVis/nagvis#41]
Even with a Role with Auth logout Permitted the logout menu don't show

**Comment by LarsMichelsen** [comment]
It may be possible that the authentication method you are using is not supporting logging out. How do you have configured authentication?

**Comment by paulrm** [comment]
Yes, I'm trying LogonMixed local users + LDAP
does LogonMixed not supporting logging out?

**Comment by LarsMichelsen** [comment]
And the LDAP authentication is done on web server level? In this case the authenticated user is handed over from the web server to NagVis and it is not possible to log out.

**Comment by paulrm** [comment]
Ok, I see. 
I'm trying to work around adding a javascript code, something link this:

```javascript
function logout() {
var url="http://redirection";    
var xmlhttp;
    if (window.XMLHttpRequest) {
          xmlhttp = new XMLHttpRequest();
    }
    // code for IE
    else if (window.ActiveXObject) {
      xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
    if (window.ActiveXObject) {
      // IE clear HTTP Authentication
      document.execCommand("ClearAuthenticationCache");
      window.location.href=$url;
    } else {
        xmlhttp.open("GET", '{URLBASE}', true, "logout", "logout");
        xmlhttp.send("");
        xmlhttp.onreadystatechange = function() {
            if (xmlhttp.readyState == 4) {window.location.href=$url;}
        }
    }
    return false;
}
```

But the most elegant way to fix this is add the necessary code to authenticate LDAP from PHP layer

**Comment by LarsMichelsen** [comment]
I don't think this is something we should integrate into NagVis. Seems a bit too hackish ;-).

Closing the issue now.
