### ISSUE TITLE
Icinga 2 / livestatus and non-existing hostgroups

### ISSUE THREAD

**Issue by pefmeister** [NagVis/nagvis#42]
If I setup a new NagVis installation on my Icinga 2 installation, I get an error with the worldmap that says "Undefined offset: 12". Digging deeper into the code the problem is that NagVis tries to search for the default groups muc and cgn through livestatus. The stats get displayed as 0;0;0;... but the first to entries hostgroup_name and hostgroup_alias are missing. Thus the index count is wrong and the error message above is generated.

The following patch adds a simple check to the GlobalBackendmklivestatus.php file for the size of the array. With that, I was able to use the geomap. I don't know if that is the best way to deal with the issue, but so far it solves the problem. Has been tested against 1.9b5. 

[GlobalBackendmklivestatus.zip](https://github.com/NagVis/nagvis/files/190195/GlobalBackendmklivestatus.zip)

Best regards,
Stephan

**Comment by LarsMichelsen** [comment]
Oh, good catch with the groups "muc" and "cgn"! Those are groups from the demo map / backend and should never be fetched from other backends like the livestatus one. I'll take a look at it.

That the index count is wrong seems to be an issue of the Icinga 2 livestatus implementation. In livestatus there should never be less columns than requested in an answer. In case a livestatus filter is not matching any object, the result set should be totally empty. Even for stats queries like this.

So maybe you should better fold a bug report on the issue tracker of Icinga 2.

**Comment by pefmeister** [comment]
Hi Lars,

I filed a bug for this (#11454). On the other hand, input checking might be a good idea anyway?!

Best regards,
Stephan

**Comment by LarsMichelsen** [comment]
Sure. At least to be compatible with current Icinga 2 versions it's a good idea to catch this kind of error. I just applied a change to handle the situation.
