### ISSUE TITLE
PHP 7 support?

### ISSUE THREAD

**Issue by nacc** [NagVis/nagvis#43]
Reading http://docs.nagvis.org/1.8/en_US/index.html, it mentions only php5. Does nagvis support PHP7? Ubuntu 16.04 packages up 1.7.10 and we are moving to a PHP7 only installation.

**Comment by LarsMichelsen** [comment]
I haven't tested it yet, but it should. Just let me know when issues occur.

**Comment by nacc** [comment]
Thanks! I'll repackage our version and let you know.

**Comment by LarsMichelsen** [comment]
Just to let you know: Yesterday I pushed some changes to the git fixing compatibility issues with PHP7.
