### ISSUE TITLE
Animation for rotation map with CSS

### ISSUE THREAD

**Issue by Azef1** [NagVis/nagvis#45]
Hi,
Currently, there aren't smooth transition between map. It's uncomfortable because there are a "white flash" when a page is loading. 
I propose to use a CSS3 animation onload page: see [here](http://jsfiddle.net/aaafrff/avvfrv5y/2/)

> html {
>     text-align: center;
>     animation: fadein 2s;
> }
> @keyframes fadein {
>     from {
>         opacity:0;
>     }
>     to {
>         opacity:1;
>     }
> }

**Comment by Azef1** [comment]
news about to implement feature ? It's possible ?

**Comment by LarsMichelsen** [comment]
Closing this inactive issue. No plan to add this by default.
