### ISSUE TITLE
Hide headershow after X second

### ISSUE THREAD

**Issue by Azef1** [NagVis/nagvis#47]
Hi, 

I suggest a feature: It's hide headershow after X second of mouse inactivity.
The headershow it's the little arrow white on top of left of the screen when all Nagvis panel are hide. The headershow it's the button to open panel of Nagvis
Why? Because on the screen it's not beautiful to see the white headershow on black map.

So,
- Hide after X second (eg: 5s) if mouse is inactive
- Show header if mouse is moving

**Comment by LarsMichelsen** [comment]
Closing old issue. No plan to implement this feature.
