### ISSUE TITLE
[Improvement] No authentification for guest user

### ISSUE THREAD

**Issue by Azef1** [NagVis/nagvis#54]
Hi,

I propose an improvement:
Disable authenfication for all guest users (read-only access). Only the admin need a login/password to do some actions (edit mode).
Currently, [http://www.nagvis.org/docs/general/faq#anchor2](http://www.nagvis.org/docs/general/faq#anchor2) this doc disable for **all** users. 
Guest user need only a read-only

What do you think ? it's possible ?

**Comment by LarsMichelsen** [comment]
Closing old issue. No plan to implement this feature.
