### ISSUE TITLE
1.9b8 context menu not visible

### ISSUE THREAD

**Issue by avelin** [NagVis/nagvis#62]
Hi, I've got:
icinga2  2.4.10-1~debmon8+1
icingaweb2  2.3.4+fix-1~debmon8+1
nagvis-1.9b8 (via livestatus)

On every map context menu is shown "under" other things -- element labels, shapes, even backgrounds:

![context1](https://cloud.githubusercontent.com/assets/7127286/17778976/abf71ef0-656e-11e6-8084-4014ffb4a6dc.png)

which makes it unusable. Same maps with version 1:1.7.10+dfsg1-3 showed the context menu on top of everything.

On a side note, element (hosts, hostgroups, etc.) labels tend to move to the right sometimes.

**Comment by LarsMichelsen** [comment]
Do you have configured the "z" attribute on your objects or do you use some kind of custom CSS?
Does the problem occur if you open the map in a dedicated tab (without the icinga GUI)?

**Comment by avelin** [comment]
* objects don't have "z" attribute, they look like this:
```
define global {
  object_id=0
  map_image=hq1bulgaria.png
  iconset=std_medium
  background_color=transparent
  grid_show=0
}

define host {
  object_id=c58b18
  host_name=hq-bulgaria-gw
  x=455
  y=144
  label_show=1
  label_background=#FFFFFF
  only_hard_states=1
}
```

* yes, I'm using custom CCS

`stylesheet="icingaweb-nagvis-integration.css"`

as described in https://github.com/Icinga/icingaweb2-module-nagvis
(which I did also use with the previous nagvis version)

* I cannot open nagvis separately, as I'm using 
`authmodule="CoreAuthModIcingaweb2"`
If after login in icingaweb, I select the nagvis frame as "open frame in new tab", the problem persists.

**Comment by LarsMichelsen** [comment]
The context menu is styled like in 1.8 and previous releases so I think your installation is somehow using old CSS files.

**Comment by avelin** [comment]
Thanks for the feedback. During upgrade of icinga2 to 2.5.3-1~debmon8+1, I've restarted the icinga2 service, and now the problem does not occur.
