### ISSUE TITLE
Nagvis Dynamic Map with Host filter grouping everything on the first host

### ISSUE THREAD

**Issue by joydragon** [NagVis/nagvis#63]
Currently I'm testing Nagvis (1.8.5) with Icinga2 (2.4.10) and Icingaweb2 (2.3.4), to generate maps based on the groups that I already have defined.

If I work with Service groups I have no issues so far, but with Host groups this weird thing happens.
![nagvis config](https://cloud.githubusercontent.com/assets/4154219/17781871/70c94514-6547-11e6-8998-27f36c6aa50c.png)
I'm using the Dynamic Map option, with the filter:
`Filter: groups >= dmz\n`
This is supposed to get me all the hosts that are part of the dmz hostgroup definition and it works, but with the first host somehow grouping a lot more errors than it should
![nagvis error](https://cloud.githubusercontent.com/assets/4154219/17781989/e32c9a5c-6547-11e6-9154-14ec3ba7c499.png)

Do you guys know if this is a bug on my configuration or if it's on the Dynamic Maps feature?

Thanks in advance

**Comment by LarsMichelsen** [comment]
I think this is a long time known issue in Icinga 2 with the kind of queries used by NagVis.
See https://dev.icinga.org/issues/7185
