### ISSUE TITLE
[only_permitted_object] can't see any object

### ISSUE THREAD

**Issue by gerpion** [NagVis/nagvis#68]
Hello,

I'm using Shinken as my monitoring solution.
I activated the module CoreAuthorisationModGroups and i'm using the perms.db file for my mapping.

This way, I can logging with my Shinken user in Nagvis and see only the map i'm allowed to.

Now, when i set only_permitted_object=1, i got the following error :

You are not permitted to access this page (Overview/view/).

Of course, i added my contact on the Hosts in Shinken.

Any clue ?

Regards,

**Comment by d-koppenhagen** [comment]
Hey I had a similar problem (same error occured). For me the following solution worked fine: https://dev.icinga.org/issues/11457

**Comment by LarsMichelsen** [comment]
Closing old issue.
