### ISSUE TITLE
geomap issues

### ISSUE THREAD

**Issue by PepeOnAChair** [NagVis/nagvis#69]
Hello,
I`ve tried a geomap and noticed a few things:
- when I select Map options - Obj. defaults - iconset - std_small, the icons looks the same like std_medium and std_dot
- labels and textboxes are not changing their size while zooming (maybe this is a feature, not a bug...)
- Would it be possible to have a parameter with every object on the map, which would define at which zoom level the object will be visible? I beleive, not all object are necessary to see when a map is zoomed out at some high level. Textboxes for example.
- And object agregation: it might be nice to by able to set at which zoom level objects belonging to the same group would be agregated as just one object (possibly as an icon). So if user zooms out higher, he will not (and he doesn`t need to) see for example icons of devices in every house in one street, but he will see agregated icon with agregated status. When user zooms in down, at some zoom level he would see icons of every single house again, so he can locate the problem.
- Would it be possible to change brightness of the map? So it would be in better contrast with objects on the map? Mostly lines might be much better visible.

Thank you for what you are doing and have a nice evening
Pepe

**Comment by LarsMichelsen** [comment]
Please check out the new worldmaps with 1.9. They don't have all features you asked for, but may be a nice alternative and maybe some of the things could be added there easier than to the geomap. But none of them is currently planned.
