### ISSUE TITLE
1.8.1 overview page

### ISSUE THREAD

**Issue by davebo** [NagVis/nagvis#7]
I'm not quite sure what to make of the new overview page.  I liked the tables and am not sure how to return to that look and feel.  attached is a screenshot showing the bottom of the page after a long list of maps.

Is this something that I can fix in the default.overview.html, or by creating a new template?

![nagvis_1 8 1](https://cloud.githubusercontent.com/assets/842907/6604393/014eddf6-c7f6-11e4-8f50-22d0eaef8683.png)

**Comment by davebo** [comment]
For perscective, here is what it looked like before the update
![nagvis_1 8rc4](https://cloud.githubusercontent.com/assets/842907/6604560/2bec94da-c7f7-11e4-8fa0-d5d95d9b4810.png)

**Comment by davebo** [comment]
As a workaround, I realize now that I can default the index page to a particular map by setting 
    [global]
    startmodule="Map"
    startshow="myMap"

Nothing to fix here, unless you want to address the layout of the overview.

**Comment by LaMi-** [comment]
Erm the layout is totally broken. This is not the intended styling. Maybe you need to clear your browser cache.

You also have old styled header template. Seems you use some local templates or old styles.

**Comment by davebo** [comment]
This is my bad.  I did not pick up the changes to the userfiles when I picked up the changes to the 1.8 branch.  It is problematic to have vendor-provided files in the same directory as user-managed files and my attempt at managing these separately did not pick up your changes.  I need to rethink how I'm going to manage these.  It would be helpful if there was a separate namespace for user managed files. (think php.ini vs php.d/*.ini , php.ini is vendor provided, php.d/*.ini is user managed).   Thanks!

**Comment by LaMi-** [comment]
Take a look at OMD, NagVis is included there. With OMD you have a local directory tree for your user changes.

But you will always have to check whether or not your custom stuff is compatinle with the new version.

**Comment by davebo** [comment]
Yes, unfortunately that (OMD) is not under my control.  All the nagios data is retrieved via mklivestatus tcp sockets (multiple nagios servers) to a standalone nagvis instance.

**Comment by LaMi-** [comment]
Solved, right? closing this...
