### ISSUE TITLE
hover_menu is too small, although browser zoom is 110%

### ISSUE THREAD

**Issue by AbdullahKh** [NagVis/nagvis#70]
Hello,
The font-size and label-size are too small in Nagvis 1.9 hover_menu. I used to use Nagvis 1.8 and all menus were fine!

![nagvis1](https://cloud.githubusercontent.com/assets/4739442/19019378/da7781fa-888e-11e6-8e79-802b3f725aff.png)

![nagvis](https://cloud.githubusercontent.com/assets/4739442/19019380/defa8a88-888e-11e6-8ac6-96302a7dcf65.png)

Is there a way to resize these menus?
Thanks!

**Comment by LarsMichelsen** [comment]
Please ensure you are using the up-to-date css definition and your browsers css cache has been cleared.

If the problem remains: Which browser+version are you using?
