### ISSUE TITLE
Nagvis map filter with icingaweb2 users and icinga2 hosts.

### ISSUE THREAD

**Issue by AbdullahKh** [NagVis/nagvis#72]
Hello,

I've some difficulties using Nagvis/map/filter with icingaweb2 users and icinga2 hosts.

I've created an icingaweb2 user named "read-only", which is only allowed to monitor hosts that belong to a certain group "group_1".
From icingaweb2 rouls, the "monitoring/filter/objects" value is "hostgroup_name=group_1" and it is working fine.

But, when I tried to use "nagvis/map/filter" I could not discover any thing!! Every time the map shows all hosts.
I've tried all the following values:
- hostgroup_name= group_1
- filter_group= group_1
- filter_group "group_1"
- Filter: filter_group "group_1"
- host_name= host_7
- host= host_7
- Filter: host_name = host_7
- map_name="Map_1"
- map="Map_1"

I have no idea how to use this filter!!

I'd really appreciate any help. Thanks in advance.

Debian 8
Icinga2.4.10-1
Icingaweb2
Nagvis 1.8
backendtype="mklivestatus"
Nagvis Map Type: Regulay map

**Comment by LarsMichelsen** [comment]
I don't really have an idea what you mean with "Nagvis/map/filter".

But: NagVis never respected the contact group assignments of nagios / icinga. By design. Some time ago the option "only_permitted_objects" has been added to nagvis.ini.php for implementing the feature you want: Show only objects the user is permitted for.

**Comment by dcneeme** [comment]
that tip to set only_permitted_objects=1 was relevant to me too. but the "wrong" hosts did not disappear from the worldmap, they just turned to blue (with summary state ERROR). 

any idea what else is needed to see only permitted hosts? v1.9.4
