### ISSUE TITLE
NagVis notifications alerts with a popup ?

### ISSUE THREAD

**Issue by SopraSteria-Romain** [NagVis/nagvis#73]
Hello fellows,

Our work team would like to implement into NagVis a popup window which rises when any event happen no matter where you are on NagVis.

Zabbix uses somekind of what we need (see the picture below on the top right corner) :
![alert_notif_wish](https://cloud.githubusercontent.com/assets/22835341/19386699/f90bd3ce-9215-11e6-8154-5cab623cc30f.png)

I've tested several modifications in the frontendEventlog.js to start adding new stuff such as the color depending on the kind of logs that occurred (green = ok, orange = warning, red = critical). That would be a starting point for us. Then we could think about "unleashing" the eventlog box and transform it as a popup window which will duplicate itself from top to down proportionnaly to the new logs events.
We also would like to store the 10 lasts events in a log file so we don't lose the logs' informations when another map is loaded.

However, we fear that it'll will require a lot of modifications in a lot of files...
So my question is: 
"Is there any thing like that which is in the roadmap and will be enable in 6 months or so ?"

Then if there is nothing planned about it, could you give us some hint about how to do that effectively please ?

Here are the modifications I've tried to implements (which don't work btw):
-------------------Added in default.css-----------------------
` #eventlog .okEventlog {
  color: green;
}
# eventlog .warningEventlog {

  color: orange;
}
# eventlog .criticalEventlog {

  color: red;
}
# eventlog .unknownEventlog {

  color: yellow;
}`

-------------------Added in frontendEventlog.js------------------
`
// Nothing changed above eventlog function in the file
function eventlog (sComponent, sSeverity, sText) {

/**
- I've decided to ignore the 1st conditional if loop and commented it
- if(typeof(oPageProperties) != 'undefined' ....
  */
  
  var doc = document;

/**
- The information log that we will store (we just add the time to it)
  */
  
  var text = getCurrentTime() + " " + sText;
  
  if (_eventlog == null) {
    eventlogInitialize();
    eventlog("eventlog", "info", "Eventlog initialized (Level: + oPageProperties.event_log_level +")");
  }

/**
- We added the else loop in order to divide up the logs further
- according to their severity and the additional css content
  */
  
  else {
    document.getElementById('eventlog').appendChild('<div class=okEventlog></div>');
    document.getElementById('eventlog').appendChild('<div class=warningEventlog></div>');
    document.getElementById('eventlog').appendChild('<div class=criticalEventlog></div>');
    document.getElementById('eventlog').appendChild('<div class=unknownEventlog></div>');
  }
  
  checkFileLog(sSeverity, text); // Call our custom function to read the logs and write it into the HTML
  
  doc = null;

/**
- Everything else below has been commented since we decided to handle
- the log limit in another way
  */

}

/**
- Function that will check if there is an existing log file
- from which we will read the 10 lasts events
- and write the new ones
- @param severity, The severity of the log event
- @param text, The informations related to the log event
  */

function checkFileLog(severity, text) {

  var file = new ActiveXObject("Scripting.FileSystemObject");
  var pathFile = "./eventlogFile.txt";
  var reader;
  var writer;
  var contentFile;
  var logInstance;
  var logsArray;
  var recentLogsArray = [];  // We want to keep only the last 10 events
  var size;
  var iteration;
  var logLimit = 10; 

  if (!file.FileExists(pathFile)) {
    file.CreateTextFile(pathFile, false); // If the file doesn't exist, we don't need to read its content
  }
  else {
    reader = file.OpenTextFile(pathFile, 1, false);
    contentFile = reader.readAll();
    reader.close();
    logsArray = contentFile.split("</br>"); // Since each log will have "</br>" at the end of its content
    size = logsArray.length - 1;
    if (size >= 0) {

```
           /**
            * We want to get the 10 last events at maximum
            */

    while (logLimit > 0 && size >= 0) {
        iteration = logsArray[size];
        recentLogsArray.push(iteration); // That array stores the 10 lasts events
        size--;
        logLimit--;
    }
    for (iteration in recentLogsArray) {
      logInstance = iteration.split(";"); // Each logs will be stored in a file like severity;information
      appendLog(logInstance[0], logInstance[1]);
    }
}
```

  }

/**
- We finally insert the new log event
  */
  
  appendLog(severity, text);
  writer = file.OpenTextFile(pathFile, 8, false);
  writer.WriteLine(severity + ";" + text + "</br>");
  writer.close();
  }

/**
- Function that will modify the HTML document
- to write the logs accordingly to their severity
- @param severity, The severity of the event to be logged
- @param text, The informations related to the event to be logged
  */

function appendLog(severity, text) {
  if (severity.toUpperCase() === 'OK') {
    document.getElementById('okEventlog').textContent += text + "</br>";
  }
  else if (severity.toUpperCase() === 'WARNING') {
    document.getElementById('warningEventlog').textContent += text + "</br>";
  }
  else if (severity.toUpperCase() === 'CRITICAL') {
    document.getElementById('criticalEventlog').textContent += text + "</br>";
  }
  else {
    document.getElementById('unknownEventlog').textContent += text + "</br>";
  }
}`

I highly thank anyone involved in the NagVis project that would take some time to read my post and think about a way to do it :) 

Please let me know if we are trying to do it the wrong way, maybe it would be simpliest to do it otherwise.

Cheers,

Romain

**Comment by LarsMichelsen** [comment]
At the moment there are no plans to implement this. Thanks for your contribution. Maybe you can get some help of other e.g. on the monitoring portal.
