### ISSUE TITLE
Nagvis 1.9 & speedometer 

### ISSUE THREAD

**Issue by amprantino** [NagVis/nagvis#74]
Hello all,

after upgrading to version 1.9b8 I cannot move arounf the speedometer:
http://docs.nagvis.org/1.9/en_US/gadgets.html
Other icons move without problem

I have also tested the current nightly (20161019) but the problem is still here.

Any ideas?

Thank you

**Comment by LarsMichelsen** [comment]
Thanks for reporting this issue. I have just fixed this issue in current master. You may verify it using the next build.

**Comment by amprantino** [comment]
Great! Thank you
