### ISSUE TITLE
double maps in sidebar. One map 'no exists'

### ISSUE THREAD

**Issue by white-line** [NagVis/nagvis#76]
That do I do:

Click on 'Export to Static Map' in worldmap - new map add in sidebar. after I delete this map via 'Options' - 'Manage Maps'.
But old map stayed in sidebar for all users, and link to no exist map ( map no see in /etc/nagvis/maps )

nagvis 1.9(b9) on Debian 8

**Comment by white-line** [comment]
Maybe this problem around local nagvis cache. Problem is gone, and I think, then I clear /path/to/nagvis/var/*

**Comment by tchene** [comment]
I have the same issue, when I delete a map, nagvis delete the map but not entry in var/maplist-full-global.cfg-1.9b10-cache and not delete too map cache file var/map-mapname.cfg-1.9b10-cache-defs.

When I change maplist content to and delete map entry, map is delete from sidebar.
