### ISSUE TITLE
error in nagvis in ubuntu 16

### ISSUE THREAD

**Issue by 6162353** [NagVis/nagvis#79]
apache2 error log:
PHP Fatal error: Redefinition of parameter $_unused_flag in /usr/share/nagvis/share/server/core/classes/objects/NagVisMapObj.php on line 247, referer: 82.199.112.138:8081/nagvis/fro…dex.php?mod=Map&act=view&show=demo-ham-racks

PHP Fatal error: Redefinition of parameter $_unused_flag in /usr/share/nagvis/share/server/core/classes/objects/NagVisMapObj.php on line 247, referer: 82.199.112.138:8081/nagvis/fro…dex.php?mod=Map&act=view&show=demo-germany

PHP Fatal error: Redefinition of parameter $_unused_flag in /usr/share/nagvis/share/server/core/classes/objects/NagVisMapObj.php on line 247, referer: 82.199.112.138:8081/nagvis/fro…dex.php?mod=Map&act=view&show=main

nagvis Версия: 1:1.7.10+dfsg1-3ubuntu1

I am using:

Ubuntu 16.04.1 LTS
Apache version Версия: 2.4.18-2ubuntu3.1
PHP version Версия: 7.0.8-0ubuntu0.16.04.2
Google chrome Версия 52.0.2743.116 m (64-bit)
Internet explorer 11.0.9600.18059

**Comment by LarsMichelsen** [comment]
Maybe you should manually install NagVis instead of using the Ubuntu package. Afaik this issue is already fixed in newer releases.
