### ISSUE TITLE
Wrong parameters in install.sh not detected

### ISSUE THREAD

**Issue by li73772** [NagVis/nagvis#8]
Hi,

when I use a wrong character in the install.sh script, it does just ignore all other parameters coming after this wrong char.

I´ve copied the string from a word document which unfortunately contains a wrong dash in the -i option. No error occurs, but it just ignores all parameters:
./install.sh –i ido2db -n /etc/icinga2 -p /usr/local/nagvis  

It would be better to get an error message that there is a wrong char in the parameter sequence.
I´m using 1.8.1 but the same behavior can be found in 1.7.10 and 1.8 as well I guess

**Comment by LaMi-** [comment]
Hi,

we use bash getopts to parse the arguments. The installer is not doing 
any custom stuff here as far as I can see.
I won't change anything here. Simply don't do it wrong.

However, if you got a simple and good patch, I'll take a look at it.

Regards
Lars

On 13.03.2015 06:52, li73772 wrote:
>
> Hi,
>
> when I use a wrong character in the install.sh script, it does just 
> ignore all other parameters coming after this wrong char.
>
> I´ve copied the string from a word document which unfortunately 
> contains a wrong dash in the -i option. No error occurs, but it just 
> ignores all parameters:
> ./install.sh –i ido2db -n /etc/icinga2 -p /usr/local/nagvis
>
> It would be better to get an error message that there is a wrong char 
> in the parameter sequence.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NagVis/nagvis/issues/8>.
>


-- 
Lars Michelsen IT
Keltenstraße 4
85586 Poing

Mobile: +49 151 26965801
E-Mail: lm@larsmichelsen.com

**Comment by li73772** [comment]
Hi, as far as I see all parameters are parsed and processed in the "while getopts" loop. So if you check after finishing the loop if anything is left, you should always receive an empty list of parameters which are left.
So something like this will do the job:

shift $(expr $OPTIND - 1 )

if [ $# -gt 0 ]; then
  echo "Found unprocessed parameters"
  exit 1
fi

Maybe additionally the unprocessed parameters should be printed out for convenience.
Right ?

**Comment by LaMi-** [comment]
Fixed it. I did it the bash way (instead of calling external program expr):

```if [ $(($#-$OPTIND)) -gt 0 ]; then
  ...
fi```
