### ISSUE TITLE
can't even get to /nagvis

### ISSUE THREAD

**Issue by elJoeyJojo** [NagVis/nagvis#80]
So I followed the "instructions" on Nagvis' http://docs.nagvis.org/1.8/en_US/index.html but they are not very helpful and does not nearly give enough details about packages to use etc...
I am stuck now where I think I installed MK Live Status, I think I installed Nagvis but can't get to the Web Interface of Nagvis for the life of me. Not even sure where to actually place the Apache configuration files and I tried to put them everywhere without luck. 

After I ran the ./install.sh script on Nagvis everything seemed to complete without any issue. Apparently if you don't touch anything else Nagvis should run right out of the box but that's not true. My server nagios.domain.com works fine but when I try nagios.domain.com/nagvis it has no idea to where to even look. The configuration folder is by default at /usr/local/nagvis and I tried copying the apach2-sample file to /etc/apache2/ and almost every other folder in the apache2 folders and no luck.

The instructions could really improve. The MK Live status is not documented at all and it doesn't explain which version and what packages to install since php5-**** on Ubuntu 14.04 is pretty much missing. It forgets to tell you to install gcc and c++ etc... 

I've spent about 2 hours trying to simply get to the nagvis web console and I pretty much gave up. The instructions are very limited with very little help. Good old Nagios will have to do.

**Comment by lupsups** [comment]
Have you had get to the nagvis web? I am also stucked ther :(
