### ISSUE TITLE
Host/Services not refreshing when shapes with images are present.

### ISSUE THREAD

**Issue by jowanw** [NagVis/nagvis#84]
I am currently experiencing a issue with my maps. When i have a shape with a pnp4nagios graph (url) that auto refreshes, my host & services stop refreshing (hover information shows last time refreshed page load time). When i remove the shapes with graphs the host & services refresh start working again.

I have noticed that when i have **interval** & **updateobjectstates** equal they both seem to work.

**Comment by LarsMichelsen** [comment]
And your NagVis version is?

**Comment by jowanw** [comment]
NagVis Version	1.8.5 (running omd)

**Comment by LarsMichelsen** [comment]
Can anybody confirm this (with 1.9x)? I was unable to reproduce it.
