### ISSUE TITLE
Integration with Centreon

### ISSUE THREAD

**Issue by joschi99** [NagVis/nagvis#87]
I would like to integrate Nagvis 1.9b11 with Centreon 2.8.x and customizing the different url links this works great. The only problem that I found is setting the 2 links for:
* host_downtime_url
* service_downtime_url
because Centreon  needs the host_id and service_id and not the host_name [host_name] and service_name [service_description].

Is there a macro in Nagvis that give us the host_id and service_id?

Regards,
Jochen

**Comment by LarsMichelsen** [comment]
NagVis does not know anything about a host_id or service_id. I won't add such thing, because I don't use Centreon. But I am open to discuss patches.

**Comment by joschi99** [comment]
Using host_id and service_id would be a great feature for a better integration not only with Centreon but also with Nagios, because the ID's are on every system the key. If you filter by name, you will get not a exact filter in every case, using the ID's this will be not a problem.
Can you understand my approach?
