### ISSUE TITLE
Unable to view hostgroups'status in Nagvis

### ISSUE THREAD

**Issue by tobias-weiss** [NagVis/nagvis#88]
I am not able to get the status of hostgroups in Nagvis. When I am in edit mode I see green icons, immeaditaly after leaving edit mode they become blue.

Normal hosts in maps do work fine. I use nagvis with mklivestatus backend.
ncat -U /var/run/icinga2/cmd/livestatus
GET hostsbygroup
does work.

====NagVis===
Version 1.9.b11
(with 1.8.x I encountered offset problems in GlobalBackendmklivestatus.php, which I was not able to fix)
===Additional info====

icinga2 - The Icinga 2 network monitoring daemon (version: v2.5.4)

Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core) [SELinux disbaled]
  Kernel: Linux
  Kernel version: 3.10.0-327.36.3.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

===nagvis.ini.php===
;; /etc/nagvis/nagvis.ini.php / 20160104
;; Marianne Spiller <github@spiller.me>
;; nagvis-1.7.10

; <?php return 1; ?>
[global]
audit_log="1"
dateformat="Y-m-d H:i:s"
file_group="apache"
file_mode=660
language="de_DE"
[paths]
base="/usr/share/nagvis/"
htmlbase="/nagvis"
htmlcgi="/icingaweb2/monitoring"
[defaults]
backend="live_1"
backgroundcolor="#ffffff"
contextmenu=1
urltarget="_parent"
hosturl="[htmlcgi]/host/show?host=[host_name]"
hostgroupurl="[htmlcgi]/list/hosts?hostgroup=[hostgroup_name]"
serviceurl="[htmlcgi]/service/show?host=[host_name]&service=[service_description]"
servicegroupurl="[htmlcgi]/list/services?servicegroup=[servicegroup_name]"
;mapurl="[htmlbase]/index.php?mod=Map&act=view&show=[map_name]"
;view_template="default"
[index]
[automap]
defaultparams="&childLayers=2"
defaultroot="some_hostname"
graphvizpath="/usr/bin/"
[wui]
[worker]
[backend_live_1]
backendtype="mklivestatus"
socket="unix:/var/run/icinga2/cmd/livestatus"
htmlcgi="/icingaweb2/monitoring"
[states]

**Comment by gao8621** [comment]
i have same err. 
my version 
    apache2.4 + php7.0
https://monitoring-portal.org/index.php?thread/39773-nagvis-1-9b11-servicegroup-hostgroup-output-error-after-refresh-host-and-service/#post243868

**Comment by gao8621** [comment]
a wordround is enable ndomy_1

but some hosts return err 
"Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'icinga2.o.name1' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"

**Comment by gao8621** [comment]
downgrade to nagvis 1.7,1.8 and check-mk 1.2.6 ,error exists.

**Comment by ibrewster** [comment]
Same issue with nagvis 1.8.5/icinga2. I can *sometimes* see more than one green (or red or whatever is appropriate), and I can *usually* get them to temporarily switch to the appropriate icon my forcing a check with the right click menu->refresh status, but it very quickly goes back to the blue icon and the false "The object does not exist" error.

**Comment by LarsMichelsen** [comment]
I am pretty sure this is caused by a bug in the Icinga 2 livestatus implementation. It exists for a longer time and no one is willing to fix this. So Livestatus does not seem to be an option with Icinga 2 anymore.

There is some work in progress to make connections with the PostgreSQL databases possible (https://github.com/NagVis/nagvis/pull/90). But this may take some time. Once it is ready we will add this backend to official NagVis code.
