### ISSUE TITLE
Endles Loading if overviews are disabled

### ISSUE THREAD

**Issue by li73772** [NagVis/nagvis#9]
Hi,

I´ve changed in config.ini.php the following parameters:
header_show_states=0
showmaps=0
showrotations=0
;[rotation_demo]
;maps="demo-germany,demo-ham-racks,demo-load,demo-muc-srv1,demo-geomap,demo-automap"
;interval=15

When I start Nagvis, it shows a "Loading..." on top, but never finishes with the task. The reason might be, that there is neither maps nor rotations to show.
I have disabled them, as my maps are quite complicated and it takes ages to show them all.
I´m using 1.8.1

**Comment by davebo** [comment]
quick suggestion, not sure if it is what you are looking for ...
If it is ok to start with one particular map, instead of the overview, you can set that in the global section
```
[global]
startmodule="Map"
startshow="MyMap"
```

**Comment by li73772** [comment]
This is not a solution to the problem, but a really good work around which is 100% fine for me. Indeed this is what I was looking for in the end ;-)
Shall I close the bug? I think the behavior is still not ok, even if the problem is solved for me.

**Comment by LaMi-** [comment]
Hi,

thanks for reporting the issue. I just fixed it the git. In fact this 
was only a visualization problem.

Best regards
Lars

On 13.03.2015 07:02, li73772 wrote:
>
> Hi,
>
> I´ve changed in config.ini.php the following parameters:
> header_show_states=0
> showmaps=0
> showrotations=0
> ;[rotation_demo]
> ;maps="demo-germany,demo-ham-racks,demo-load,demo-muc-srv1,demo-geomap,demo-automap"
> ;interval=15
>
> When I start Nagvis, it shows a "Loading..." on top, but never 
> finishes with the task. The reason might be, that there is neither 
> maps nor rotations to show.
> I have disabled them, as my maps are quite complicated and it takes 
> ages to show them all.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NagVis/nagvis/issues/9>.
>


-- 
Lars Michelsen IT
Keltenstraße 4
85586 Poing

Mobile: +49 151 26965801
E-Mail: lm@larsmichelsen.com

**Comment by LaMi-** [comment]
Closed.
