### ISSUE TITLE
Zoom error

### ISSUE THREAD

**Issue by LaFong** [NagVis/nagvis#94]
When zooming into a geomap, level 9+, I get this error:
`Javascript error occured: Uncaught TypeError: Cannot read property 'addChild' of undefined http://192.168.1.1/nagvis/frontend/nagvis-js/js/NagVisCompressed.js (4309)`

I have tried it with and without NagVisCompressed.js, same error.
This error has also happened to another user, on the forum.

We are at v1.9b8. With latest ViewMap.js and nagvis/share/server/core/classes/ViewMapAddModify.php files, this is the debug output:

`ViewMap.js:232 Uncaught TypeError: Cannot read property 'addChild' of undefined at proto.constructor.renderObject (ViewMap.js:232) at proto.constructor.initializeObjects (ViewMap.js:262) at proto.constructor.handleMapInit (ViewMap.js:136) at XMLHttpRequest.AJAX.onreadystatechange (ajax.js:95) renderObject    @    ViewMap.js:232 initializeObjects    @    ViewMap.js:262 handleMapInit    @    ViewMap.js:136 AJAX.onreadystatechange    @    ajax.js:95`

**Comment by LaFong** [comment]
This error seems to be due to the separation between points, and possibly map center or zoom point. If I put two points right next to each other I can zoom all the way to level 18, no error. If I put 2 points at opposite ends of NY state, it errors at level 12. If I put one point in NY and one in Hawaii, it errors out at level 8. With a point in Christchurch, NZ and one in northern Spain at the opposite end of the world, it errors between 6 and 9, depending on where the map is centered and what point you zoom into.

**Comment by LarsMichelsen** [comment]
Please check out the new worldmap which may be a better alternative for you. I have no plan to invest more time in the geomap anymore.

**Comment by LaFong** [comment]
Woops. I meant worldmap, my apologies. So, this problem exists with the current mapping.

**Comment by ekrichbaum** [comment]
Got a little time to work here.  Problem exists in the renderObject function where .childs is undefined. This causes the addChild(obj) to fail.

Doesn't fix how we got here but adding a check before the call seems to correct the issue.

if (obj.childs.length != 0) this.objects[parentObjId].addChild(obj);

Fix in NagVisCompressed.js and ViewMap.js
