### ISSUE TITLE
Error: (0) in_array() expects parameter 2 to be array, boolean given

### ISSUE THREAD

**Issue by jowanw** [NagVis/nagvis#97]
Nagvis version: 1.9b8
Error when going to any page:

Error: (0) in_array() expects parameter 2 to be array, boolean given
URL: /sitename/nagvis/frontend/nagvis-js/index.php
File: /opt/omd/versions/2.21.20170324-labs-edition/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php
Line: 1006
#0 [internal function]: nagvisExceptionErrorHandler(2, 'in_array() expe...', '/opt/omd/versio...', 1006, Array)
#1 /opt/omd/versions/2.21.20170324-labs-edition/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php(996): in_array('worldmap', false)
#2 /opt/omd/versions/2.21.20170324-labs-edition/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php(465): GlobalMapCfg->checkMapConfigIsValid()
#3 /opt/omd/versions/2.21.20170324-labs-edition/share/nagvis/htdocs/frontend/nagvis-js/classes/NagVisHeaderMenu.php(164): GlobalMapCfg->readMapConfig(true)
#4 /opt/omd/versions/2.21.20170324-labs-edition/share/nagvis/htdocs/frontend/nagvis-js/classes/NagVisHeaderMenu.php(305): NagVisHeaderMenu->getMapList()
#5 /opt/omd/versions/2.21.20170324-labs-edition/share/nagvis/htdocs/frontend/nagvis-js/classes/NagVisHeaderMenu.php(82): NagVisHeaderMenu->getMacros()
#6 /opt/omd/versions/2.21.20170324-labs-edition/share/nagvis/htdocs/frontend/nagvis-js/classes/FrontendModOverview.php(77): NagVisHeaderMenu->__toString()
#7 /opt/omd/versions/2.21.20170324-labs-edition/share/nagvis/htdocs/frontend/nagvis-js/classes/FrontendModOverview.php(55): FrontendModOverview->showViewDialog()
#8 /opt/omd/versions/2.21.20170324-labs-edition/share/nagvis/htdocs/server/core/functions/index.php(120): FrontendModOverview->handleAction()
#9 /opt/omd/versions/2.21.20170324-labs-edition/share/nagvis/htdocs/frontend/nagvis-js/index.php(53): require('/opt/omd/versio...')
#10 {main}

**Comment by jowanw** [comment]
Fixed, something with one of our maps.

**Comment by Yuvaraj89888** [comment]
hi,
please let me know what you have done to fix this
